<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.8">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Colin Madland">
<meta name="dcterms.date" content="2024-04-26">

<title>dsus_18 - Exploratory Factor Analysis – Learning | Assessment | Technology</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-79bb3942e891885f9f7af119cd221462.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-99e42d58961487636930fdd71fdb3421.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Learning | Assessment | Technology</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/cmadland/blog"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://bsky.app/profile/cmad.land"> <i class="bi bi-bluesky" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">dsus_18 - Exploratory Factor Analysis</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">EFA</div>
                <div class="quarto-category">dsur</div>
                <div class="quarto-category">dsus</div>
                <div class="quarto-category">R</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Colin Madland </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">April 26, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse, knitr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.1     ✔ stringr   1.5.2
✔ ggplot2   4.0.0     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2, ggfortify, robust)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: viridisLite</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GPArotation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>raq_tib <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data/raq.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  readr<span class="sc">::</span><span class="fu">read_csv</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 2571 Columns: 24
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (1): id
dbl (23): raq_01, raq_02, raq_03, raq_04, raq_05, raq_06, raq_07, raq_08, ra...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>Notes here are from</p>
<p>Field, A. P. (2018). <em>Discovering statistics using IBM SPSS statistics</em> (5th edition, North American edition). Sage Publications Inc.&nbsp;-&gt; <code>DSuS</code></p>
<p>Code examples will be from:</p>
<p>Field, A. (2023). discovr: Interactive tutorials and data for “Discovering Statistics Using R and RStudio” [Manual]. -&gt; <code>discovr</code></p>
<p>R Core Team. (2023). R: A language and environment for statistical computing [Manual]. R Foundation for Statistical Computing. https://www.R-project.org/</p>
<section id="when-to-use-factor-analysis-p.-571" class="level2">
<h2 class="anchored" data-anchor-id="when-to-use-factor-analysis-p.-571">When to use factor analysis (p.&nbsp;571)</h2>
<ul>
<li>when attempting to measure latent variables</li>
<li>factor analysis and principal component analysis are used to identify clusters of variables</li>
<li>3 main uses
<ul>
<li>understand the structure of a set of variables</li>
<li>to construct a questionnaire to measure an underlying variable</li>
<li>reduce the size of a data set while retaining as much of the original information as possible
<ul>
<li>(FA can be used to solve the problem of multicollinearity by combining factors that are collinear)</li>
</ul></li>
</ul></li>
</ul>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<dl>
<dt><code>multicollinearity</code></dt>
<dd>
<p>exists when there is a strong correlation between two factors</p>
</dd>
<dd>
<p>multicollinearity makes it difficult or impossible to determine the amount of variance accounted for by one of two correlated factors</p>
</dd>
<dd>
<p>e.g., if a factor predicts the outcome variable with <span class="math inline">\(R=0.80\)</span> and a second variable accounts for <em>the same variance</em> (i.e., it is highly correlated to the first variable) then it is only contributing to a very small amount of the unique variance in outcome and we might see <span class="math inline">\(R=0.82\)</span>. If the two predictor variables are uncorrelated, then the second variable is contributing more unique variance and we might see <span class="math inline">\(R=0.95\)</span></p>
</dd>
<dd>
<p>multicollinearity leads to interchangable predictors</p>
</dd>
</dl>
</div>
</div>
</div>
<section id="examples-of-factor-analysis" class="level3">
<h3 class="anchored" data-anchor-id="examples-of-factor-analysis">Examples of factor analysis</h3>
<ul>
<li>extroversion, introversion, neuroticism traits</li>
<li>personality questionnaires</li>
<li>in economics to see whether productivity, profits, and workforce contribute to the underlying dimension of company growth</li>
</ul>
</section>
<section id="efa-and-pca" class="level3">
<h3 class="anchored" data-anchor-id="efa-and-pca">EFA and PCA</h3>
<ul>
<li>they are not the same thing</li>
<li>but they both are used to reduce a set of variables into a smaller set of dimensions (factors in EFA, and components in PCA)</li>
</ul>
</section>
</section>
<section id="factors-and-components" class="level2">
<h2 class="anchored" data-anchor-id="factors-and-components">Factors and Components</h2>
<ul>
<li><p>measuring several variables with several questions gives us data that can be arranged in a correlation matrix (R matrix) as below. <img src="cor-matrix.png" class="img-fluid" alt="Example of a correlation matrix"></p>
<p><em>Note:</em> Created with the <code>ggplot2</code> R package <span class="citation" data-cites="wickham2016">(<a href="#ref-wickham2016" role="doc-biblioref">Wickham 2016</a>)</span> with data from the <code>discovr</code> package <span class="citation" data-cites="field2023">(<a href="#ref-field2023" role="doc-biblioref">Field 2023</a>.)</span></p></li>
<li><p>factor analysis tries to explain the maximum amount of <em>common variance</em> in the matrix using the least number of explanatory constructs (latent variables), which represent clusters of variables that correlate highly with each other.</p></li>
<li><p>PCA differs in that it tries to explain the maximum amount of <em>total variance</em> in a correlation matrix by transforming the original variables into linear components</p></li>
</ul>
</section>
<section id="example---induced-anxiety-discovr_18-field2023" class="level2">
<h2 class="anchored" data-anchor-id="example---induced-anxiety-discovr_18-field2023">Example - Induced Anxiety (<code>discovr_18</code> <span class="citation" data-cites="field2023">Field (<a href="#ref-field2023" role="doc-biblioref">2023</a>)</span>)</h2>
<ul>
<li>questionnaire developed to measure anxiety related to using R</li>
<li>questions developed from interviews with anxious and non-anxious students</li>
<li>23 questions; 5-point likert (strongly disagree -&gt; strongly agree)
<ul>
<li>raq_01: Statistics make me cry</li>
<li>raq_02: My friends will think I’m stupid for not being able to cope with R</li>
<li>raq_03: Standard deviations excite me</li>
<li>raq_04: I dream that Pearson is attacking me with correlation coefficients</li>
<li>raq_05: I don’t understand statistics</li>
<li>raq_06: I have little experience of computers</li>
<li>raq_07: All computers hate me</li>
<li>raq_08: I have never been good at mathematics</li>
<li>raq_09: My friends are better at statistics than me</li>
<li>raq_10: Computers are useful only for playing games</li>
<li>raq_11: I did badly at mathematics at school</li>
<li>raq_12: People try to tell you that R makes statistics easier to understand but it doesn’t</li>
<li>raq_13: I worry that I will cause irreparable damage because of my incompetence with computers</li>
<li>raq_14: Computers have minds of their own and deliberately go wrong whenever I use them</li>
<li>raq_15: Computers are out to get me</li>
<li>raq_16: I weep openly at the mention of central tendency</li>
<li>raq_17: I slip into a coma whenever I see an equation</li>
<li>raq_18: R always crashes when I try to use it</li>
<li>raq_19: Everybody looks at me when I use R</li>
<li>raq_20: I can’t sleep for thoughts of eigenvectors</li>
<li>raq_21: I wake up under my duvet thinking that I am trapped under a normal distribution</li>
<li>raq_22: My friends are better at R than I am</li>
<li>raq_23: If I am good at statistics people will think I am a nerd</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>raq_tib</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,571 × 24
   id    raq_01 raq_02 raq_03 raq_04 raq_05 raq_06 raq_07 raq_08 raq_09 raq_10
   &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 157lk      3      1      3      4      2      4      3      3      3      2
 2 k3xjh      2      5      3      3      4      4      5      4      4      3
 3 832x6      4      5      3      3      3      4      5      4      3      4
 4 6dyt5      4      4      4      3      4      4      4      3      2      2
 5 w4upu      4      2      5      4      2      3      2      5      4      5
 6 9432i      2      3      4      3      4      2      3      2      3      2
 7 x03sh      2      4      5      5      3      3      4      3      3      3
 8 12v15      4      3      4      3      5      4      5      4      3      5
 9 46y22      3      5      5      1      3      4      4      3      5      3
10 1iqc4      2      5      3      2      4      5      5      5      4      4
# ℹ 2,561 more rows
# ℹ 13 more variables: raq_11 &lt;dbl&gt;, raq_12 &lt;dbl&gt;, raq_13 &lt;dbl&gt;, raq_14 &lt;dbl&gt;,
#   raq_15 &lt;dbl&gt;, raq_16 &lt;dbl&gt;, raq_17 &lt;dbl&gt;, raq_18 &lt;dbl&gt;, raq_19 &lt;dbl&gt;,
#   raq_20 &lt;dbl&gt;, raq_21 &lt;dbl&gt;, raq_22 &lt;dbl&gt;, raq_23 &lt;dbl&gt;</code></pre>
</div>
</div>
<ul>
<li>24 variables including the ID</li>
<li>we don’t need the <code>id</code> in analyses so create a new tib without it</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>raq_items_tib <span class="ot">&lt;-</span> raq_tib <span class="sc">|&gt;</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>id)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>raq_items_tib</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,571 × 23
   raq_01 raq_02 raq_03 raq_04 raq_05 raq_06 raq_07 raq_08 raq_09 raq_10 raq_11
    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1      3      1      3      4      2      4      3      3      3      2      2
 2      2      5      3      3      4      4      5      4      4      3      4
 3      4      5      3      3      3      4      5      4      3      4      4
 4      4      4      4      3      4      4      4      3      2      2      2
 5      4      2      5      4      2      3      2      5      4      5      4
 6      2      3      4      3      4      2      3      2      3      2      1
 7      2      4      5      5      3      3      4      3      3      3      3
 8      4      3      4      3      5      4      5      4      3      5      3
 9      3      5      5      1      3      4      4      3      5      3      3
10      2      5      3      2      4      5      5      5      4      4      4
# ℹ 2,561 more rows
# ℹ 12 more variables: raq_12 &lt;dbl&gt;, raq_13 &lt;dbl&gt;, raq_14 &lt;dbl&gt;, raq_15 &lt;dbl&gt;,
#   raq_16 &lt;dbl&gt;, raq_17 &lt;dbl&gt;, raq_18 &lt;dbl&gt;, raq_19 &lt;dbl&gt;, raq_20 &lt;dbl&gt;,
#   raq_21 &lt;dbl&gt;, raq_22 &lt;dbl&gt;, raq_23 &lt;dbl&gt;</code></pre>
</div>
</div>
<section id="correlation-matrix" class="level3">
<h3 class="anchored" data-anchor-id="correlation-matrix">Correlation matrix</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># feed the tibble with only the RAQ items into the correlation() function</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>correlation<span class="sc">::</span><span class="fu">correlation</span>(raq_items_tib)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Correlation Matrix (pearson-method)

Parameter1 | Parameter2 |     r |         95% CI | t(2569) |         p
----------------------------------------------------------------------
raq_01     |     raq_02 |  0.11 | [ 0.07,  0.15] |    5.47 | &lt; .001***
raq_01     |     raq_03 | -0.18 | [-0.22, -0.14] |   -9.21 | &lt; .001***
raq_01     |     raq_04 |  0.22 | [ 0.18,  0.25] |   11.26 | &lt; .001***
raq_01     |     raq_05 |  0.22 | [ 0.19,  0.26] |   11.60 | &lt; .001***
raq_01     |     raq_06 |  0.16 | [ 0.12,  0.20] |    8.17 | &lt; .001***
raq_01     |     raq_07 |  0.11 | [ 0.07,  0.14] |    5.41 | &lt; .001***
raq_01     |     raq_08 |  0.22 | [ 0.18,  0.26] |   11.53 | &lt; .001***
raq_01     |     raq_09 |  0.08 | [ 0.05,  0.12] |    4.26 | &lt; .001***
raq_01     |     raq_10 |  0.11 | [ 0.07,  0.15] |    5.70 | &lt; .001***
raq_01     |     raq_11 |  0.19 | [ 0.15,  0.23] |    9.76 | &lt; .001***
raq_01     |     raq_12 |  0.15 | [ 0.11,  0.19] |    7.67 | &lt; .001***
raq_01     |     raq_13 |  0.11 | [ 0.07,  0.15] |    5.55 | &lt; .001***
raq_01     |     raq_14 |  0.12 | [ 0.08,  0.15] |    5.87 | &lt; .001***
raq_01     |     raq_15 |  0.11 | [ 0.07,  0.15] |    5.61 | &lt; .001***
raq_01     |     raq_16 |  0.18 | [ 0.14,  0.21] |    9.04 | &lt; .001***
raq_01     |     raq_17 |  0.17 | [ 0.13,  0.20] |    8.52 | &lt; .001***
raq_01     |     raq_18 |  0.12 | [ 0.08,  0.16] |    6.06 | &lt; .001***
raq_01     |     raq_19 |  0.11 | [ 0.07,  0.14] |    5.45 | &lt; .001***
raq_01     |     raq_20 |  0.21 | [ 0.17,  0.24] |   10.73 | &lt; .001***
raq_01     |     raq_21 |  0.23 | [ 0.19,  0.26] |   11.81 | &lt; .001***
raq_01     |     raq_22 |  0.12 | [ 0.09,  0.16] |    6.30 | &lt; .001***
raq_01     |     raq_23 |  0.08 | [ 0.04,  0.12] |    3.93 | &lt; .001***
raq_02     |     raq_03 | -0.12 | [-0.16, -0.08] |   -6.14 | &lt; .001***
raq_02     |     raq_04 |  0.12 | [ 0.09,  0.16] |    6.31 | &lt; .001***
raq_02     |     raq_05 |  0.28 | [ 0.24,  0.31] |   14.71 | &lt; .001***
raq_02     |     raq_06 |  0.34 | [ 0.30,  0.37] |   18.19 | &lt; .001***
raq_02     |     raq_07 |  0.26 | [ 0.22,  0.29] |   13.44 | &lt; .001***
raq_02     |     raq_08 |  0.18 | [ 0.14,  0.22] |    9.16 | &lt; .001***
raq_02     |     raq_09 |  0.39 | [ 0.36,  0.42] |   21.50 | &lt; .001***
raq_02     |     raq_10 |  0.18 | [ 0.15,  0.22] |    9.48 | &lt; .001***
raq_02     |     raq_11 |  0.15 | [ 0.11,  0.19] |    7.82 | &lt; .001***
raq_02     |     raq_12 |  0.09 | [ 0.05,  0.13] |    4.58 | &lt; .001***
raq_02     |     raq_13 |  0.23 | [ 0.19,  0.27] |   11.96 | &lt; .001***
raq_02     |     raq_14 |  0.20 | [ 0.16,  0.23] |   10.21 | &lt; .001***
raq_02     |     raq_15 |  0.19 | [ 0.15,  0.22] |    9.64 | &lt; .001***
raq_02     |     raq_16 |  0.10 | [ 0.06,  0.13] |    4.92 | &lt; .001***
raq_02     |     raq_17 |  0.17 | [ 0.14,  0.21] |    8.94 | &lt; .001***
raq_02     |     raq_18 |  0.26 | [ 0.23,  0.30] |   13.87 | &lt; .001***
raq_02     |     raq_19 |  0.39 | [ 0.36,  0.42] |   21.50 | &lt; .001***
raq_02     |     raq_20 |  0.13 | [ 0.09,  0.17] |    6.55 | &lt; .001***
raq_02     |     raq_21 |  0.16 | [ 0.12,  0.20] |    8.26 | &lt; .001***
raq_02     |     raq_22 |  0.34 | [ 0.30,  0.37] |   18.28 | &lt; .001***
raq_02     |     raq_23 |  0.39 | [ 0.36,  0.42] |   21.56 | &lt; .001***
raq_03     |     raq_04 | -0.19 | [-0.23, -0.16] |  -10.01 | &lt; .001***
raq_03     |     raq_05 | -0.25 | [-0.29, -0.22] |  -13.34 | &lt; .001***
raq_03     |     raq_06 | -0.17 | [-0.20, -0.13] |   -8.51 | &lt; .001***
raq_03     |     raq_07 | -0.13 | [-0.16, -0.09] |   -6.45 | &lt; .001***
raq_03     |     raq_08 | -0.22 | [-0.25, -0.18] |  -11.33 | &lt; .001***
raq_03     |     raq_09 | -0.08 | [-0.12, -0.04] |   -4.14 | &lt; .001***
raq_03     |     raq_10 | -0.10 | [-0.14, -0.06] |   -5.18 | &lt; .001***
raq_03     |     raq_11 | -0.19 | [-0.23, -0.15] |   -9.81 | &lt; .001***
raq_03     |     raq_12 | -0.15 | [-0.19, -0.11] |   -7.58 | &lt; .001***
raq_03     |     raq_13 | -0.13 | [-0.17, -0.09] |   -6.71 | &lt; .001***
raq_03     |     raq_14 | -0.09 | [-0.13, -0.05] |   -4.45 | &lt; .001***
raq_03     |     raq_15 | -0.15 | [-0.19, -0.11] |   -7.57 | &lt; .001***
raq_03     |     raq_16 | -0.20 | [-0.24, -0.17] |  -10.56 | &lt; .001***
raq_03     |     raq_17 | -0.18 | [-0.21, -0.14] |   -9.01 | &lt; .001***
raq_03     |     raq_18 | -0.15 | [-0.19, -0.11] |   -7.78 | &lt; .001***
raq_03     |     raq_19 | -0.12 | [-0.15, -0.08] |   -5.96 | &lt; .001***
raq_03     |     raq_20 | -0.23 | [-0.27, -0.20] |  -12.20 | &lt; .001***
raq_03     |     raq_21 | -0.26 | [-0.30, -0.22] |  -13.62 | &lt; .001***
raq_03     |     raq_22 | -0.12 | [-0.16, -0.08] |   -6.00 | &lt; .001***
raq_03     |     raq_23 | -0.05 | [-0.09, -0.01] |   -2.65 | 0.014*   
raq_04     |     raq_05 |  0.32 | [ 0.28,  0.35] |   17.08 | &lt; .001***
raq_04     |     raq_06 |  0.23 | [ 0.20,  0.27] |   12.21 | &lt; .001***
raq_04     |     raq_07 |  0.17 | [ 0.13,  0.20] |    8.56 | &lt; .001***
raq_04     |     raq_08 |  0.25 | [ 0.21,  0.28] |   12.96 | &lt; .001***
raq_04     |     raq_09 |  0.10 | [ 0.06,  0.14] |    4.98 | &lt; .001***
raq_04     |     raq_10 |  0.18 | [ 0.14,  0.21] |    9.11 | &lt; .001***
raq_04     |     raq_11 |  0.22 | [ 0.18,  0.26] |   11.54 | &lt; .001***
raq_04     |     raq_12 |  0.20 | [ 0.16,  0.23] |   10.12 | &lt; .001***
raq_04     |     raq_13 |  0.16 | [ 0.13,  0.20] |    8.42 | &lt; .001***
raq_04     |     raq_14 |  0.15 | [ 0.11,  0.18] |    7.55 | &lt; .001***
raq_04     |     raq_15 |  0.18 | [ 0.15,  0.22] |    9.50 | &lt; .001***
raq_04     |     raq_16 |  0.27 | [ 0.23,  0.31] |   14.25 | &lt; .001***
raq_04     |     raq_17 |  0.24 | [ 0.20,  0.27] |   12.36 | &lt; .001***
raq_04     |     raq_18 |  0.17 | [ 0.13,  0.21] |    8.81 | &lt; .001***
raq_04     |     raq_19 |  0.14 | [ 0.10,  0.18] |    7.24 | &lt; .001***
raq_04     |     raq_20 |  0.28 | [ 0.25,  0.32] |   15.00 | &lt; .001***
raq_04     |     raq_21 |  0.32 | [ 0.28,  0.35] |   17.12 | &lt; .001***
raq_04     |     raq_22 |  0.16 | [ 0.12,  0.19] |    8.07 | &lt; .001***
raq_04     |     raq_23 |  0.08 | [ 0.04,  0.12] |    4.22 | &lt; .001***
raq_05     |     raq_06 |  0.51 | [ 0.48,  0.54] |   30.26 | &lt; .001***
raq_05     |     raq_07 |  0.36 | [ 0.33,  0.40] |   19.79 | &lt; .001***
raq_05     |     raq_08 |  0.36 | [ 0.32,  0.39] |   19.39 | &lt; .001***
raq_05     |     raq_09 |  0.16 | [ 0.12,  0.20] |    8.28 | &lt; .001***
raq_05     |     raq_10 |  0.31 | [ 0.28,  0.35] |   16.67 | &lt; .001***
raq_05     |     raq_11 |  0.31 | [ 0.28,  0.35] |   16.61 | &lt; .001***
raq_05     |     raq_12 |  0.19 | [ 0.15,  0.22] |    9.66 | &lt; .001***
raq_05     |     raq_13 |  0.35 | [ 0.32,  0.38] |   19.00 | &lt; .001***
raq_05     |     raq_14 |  0.27 | [ 0.23,  0.30] |   14.05 | &lt; .001***
raq_05     |     raq_15 |  0.33 | [ 0.29,  0.36] |   17.54 | &lt; .001***
raq_05     |     raq_16 |  0.24 | [ 0.20,  0.28] |   12.53 | &lt; .001***
raq_05     |     raq_17 |  0.30 | [ 0.27,  0.34] |   16.01 | &lt; .001***
raq_05     |     raq_18 |  0.38 | [ 0.35,  0.41] |   20.97 | &lt; .001***
raq_05     |     raq_19 |  0.29 | [ 0.26,  0.33] |   15.50 | &lt; .001***
raq_05     |     raq_20 |  0.34 | [ 0.31,  0.37] |   18.36 | &lt; .001***
raq_05     |     raq_21 |  0.37 | [ 0.34,  0.40] |   20.24 | &lt; .001***
raq_05     |     raq_22 |  0.27 | [ 0.23,  0.31] |   14.26 | &lt; .001***
raq_05     |     raq_23 |  0.17 | [ 0.13,  0.21] |    8.70 | &lt; .001***
raq_06     |     raq_07 |  0.45 | [ 0.42,  0.48] |   25.68 | &lt; .001***
raq_06     |     raq_08 |  0.34 | [ 0.31,  0.37] |   18.36 | &lt; .001***
raq_06     |     raq_09 |  0.20 | [ 0.16,  0.24] |   10.40 | &lt; .001***
raq_06     |     raq_10 |  0.40 | [ 0.36,  0.43] |   21.93 | &lt; .001***
raq_06     |     raq_11 |  0.29 | [ 0.26,  0.33] |   15.55 | &lt; .001***
raq_06     |     raq_12 |  0.11 | [ 0.07,  0.15] |    5.74 | &lt; .001***
raq_06     |     raq_13 |  0.46 | [ 0.42,  0.49] |   25.90 | &lt; .001***
raq_06     |     raq_14 |  0.36 | [ 0.32,  0.39] |   19.25 | &lt; .001***
raq_06     |     raq_15 |  0.40 | [ 0.37,  0.43] |   22.20 | &lt; .001***
raq_06     |     raq_16 |  0.16 | [ 0.12,  0.20] |    8.21 | &lt; .001***
raq_06     |     raq_17 |  0.28 | [ 0.24,  0.32] |   14.83 | &lt; .001***
raq_06     |     raq_18 |  0.51 | [ 0.48,  0.54] |   30.01 | &lt; .001***
raq_06     |     raq_19 |  0.38 | [ 0.34,  0.41] |   20.64 | &lt; .001***
raq_06     |     raq_20 |  0.23 | [ 0.19,  0.26] |   11.74 | &lt; .001***
raq_06     |     raq_21 |  0.26 | [ 0.23,  0.30] |   13.86 | &lt; .001***
raq_06     |     raq_22 |  0.33 | [ 0.29,  0.36] |   17.48 | &lt; .001***
raq_06     |     raq_23 |  0.17 | [ 0.13,  0.21] |    8.85 | &lt; .001***
raq_07     |     raq_08 |  0.25 | [ 0.21,  0.28] |   13.03 | &lt; .001***
raq_07     |     raq_09 |  0.17 | [ 0.13,  0.20] |    8.48 | &lt; .001***
raq_07     |     raq_10 |  0.28 | [ 0.25,  0.32] |   14.94 | &lt; .001***
raq_07     |     raq_11 |  0.21 | [ 0.18,  0.25] |   11.02 | &lt; .001***
raq_07     |     raq_12 |  0.10 | [ 0.06,  0.13] |    4.89 | &lt; .001***
raq_07     |     raq_13 |  0.31 | [ 0.28,  0.35] |   16.58 | &lt; .001***
raq_07     |     raq_14 |  0.25 | [ 0.21,  0.29] |   13.16 | &lt; .001***
raq_07     |     raq_15 |  0.29 | [ 0.25,  0.32] |   15.28 | &lt; .001***
raq_07     |     raq_16 |  0.12 | [ 0.08,  0.16] |    6.21 | &lt; .001***
raq_07     |     raq_17 |  0.21 | [ 0.17,  0.25] |   10.94 | &lt; .001***
raq_07     |     raq_18 |  0.35 | [ 0.32,  0.38] |   18.93 | &lt; .001***
raq_07     |     raq_19 |  0.26 | [ 0.22,  0.29] |   13.41 | &lt; .001***
raq_07     |     raq_20 |  0.14 | [ 0.10,  0.18] |    7.17 | &lt; .001***
raq_07     |     raq_21 |  0.20 | [ 0.16,  0.23] |   10.19 | &lt; .001***
raq_07     |     raq_22 |  0.22 | [ 0.19,  0.26] |   11.69 | &lt; .001***
raq_07     |     raq_23 |  0.16 | [ 0.12,  0.20] |    8.24 | &lt; .001***
raq_08     |     raq_09 |  0.16 | [ 0.13,  0.20] |    8.45 | &lt; .001***
raq_08     |     raq_10 |  0.19 | [ 0.15,  0.22] |    9.58 | &lt; .001***
raq_08     |     raq_11 |  0.58 | [ 0.56,  0.61] |   36.28 | &lt; .001***
raq_08     |     raq_12 |  0.13 | [ 0.09,  0.17] |    6.58 | &lt; .001***
raq_08     |     raq_13 |  0.20 | [ 0.16,  0.24] |   10.38 | &lt; .001***
raq_08     |     raq_14 |  0.23 | [ 0.19,  0.27] |   12.01 | &lt; .001***
raq_08     |     raq_15 |  0.23 | [ 0.19,  0.27] |   11.97 | &lt; .001***
raq_08     |     raq_16 |  0.21 | [ 0.17,  0.24] |   10.69 | &lt; .001***
raq_08     |     raq_17 |  0.55 | [ 0.52,  0.57] |   33.20 | &lt; .001***
raq_08     |     raq_18 |  0.28 | [ 0.24,  0.31] |   14.68 | &lt; .001***
raq_08     |     raq_19 |  0.21 | [ 0.17,  0.25] |   10.86 | &lt; .001***
raq_08     |     raq_20 |  0.26 | [ 0.23,  0.30] |   13.76 | &lt; .001***
raq_08     |     raq_21 |  0.30 | [ 0.27,  0.34] |   16.15 | &lt; .001***
raq_08     |     raq_22 |  0.22 | [ 0.19,  0.26] |   11.68 | &lt; .001***
raq_08     |     raq_23 |  0.14 | [ 0.10,  0.18] |    7.25 | &lt; .001***
raq_09     |     raq_10 |  0.11 | [ 0.07,  0.14] |    5.38 | &lt; .001***
raq_09     |     raq_11 |  0.17 | [ 0.14,  0.21] |    9.01 | &lt; .001***
raq_09     |     raq_12 |  0.06 | [ 0.02,  0.10] |    3.07 | 0.007**  
raq_09     |     raq_13 |  0.15 | [ 0.11,  0.19] |    7.84 | &lt; .001***
raq_09     |     raq_14 |  0.12 | [ 0.09,  0.16] |    6.30 | &lt; .001***
raq_09     |     raq_15 |  0.15 | [ 0.11,  0.19] |    7.60 | &lt; .001***
raq_09     |     raq_16 |  0.08 | [ 0.04,  0.12] |    4.19 | &lt; .001***
raq_09     |     raq_17 |  0.14 | [ 0.10,  0.18] |    7.32 | &lt; .001***
raq_09     |     raq_18 |  0.15 | [ 0.11,  0.18] |    7.52 | &lt; .001***
raq_09     |     raq_19 |  0.46 | [ 0.43,  0.49] |   26.59 | &lt; .001***
raq_09     |     raq_20 |  0.10 | [ 0.06,  0.14] |    5.08 | &lt; .001***
raq_09     |     raq_21 |  0.17 | [ 0.13,  0.20] |    8.61 | &lt; .001***
raq_09     |     raq_22 |  0.43 | [ 0.40,  0.46] |   23.95 | &lt; .001***
raq_09     |     raq_23 |  0.55 | [ 0.52,  0.57] |   33.09 | &lt; .001***
raq_10     |     raq_11 |  0.17 | [ 0.13,  0.21] |    8.68 | &lt; .001***
raq_10     |     raq_12 |  0.08 | [ 0.04,  0.11] |    3.85 | 0.001**  
raq_10     |     raq_13 |  0.25 | [ 0.21,  0.28] |   12.99 | &lt; .001***
raq_10     |     raq_14 |  0.22 | [ 0.18,  0.26] |   11.38 | &lt; .001***
raq_10     |     raq_15 |  0.24 | [ 0.21,  0.28] |   12.68 | &lt; .001***
raq_10     |     raq_16 |  0.13 | [ 0.09,  0.17] |    6.59 | &lt; .001***
raq_10     |     raq_17 |  0.18 | [ 0.14,  0.21] |    9.12 | &lt; .001***
raq_10     |     raq_18 |  0.29 | [ 0.26,  0.33] |   15.43 | &lt; .001***
raq_10     |     raq_19 |  0.21 | [ 0.17,  0.25] |   10.97 | &lt; .001***
raq_10     |     raq_20 |  0.18 | [ 0.14,  0.22] |    9.23 | &lt; .001***
raq_10     |     raq_21 |  0.16 | [ 0.12,  0.20] |    8.34 | &lt; .001***
raq_10     |     raq_22 |  0.16 | [ 0.12,  0.19] |    7.98 | &lt; .001***
raq_10     |     raq_23 |  0.07 | [ 0.03,  0.11] |    3.53 | 0.003**  
raq_11     |     raq_12 |  0.10 | [ 0.07,  0.14] |    5.27 | &lt; .001***
raq_11     |     raq_13 |  0.20 | [ 0.16,  0.24] |   10.40 | &lt; .001***
raq_11     |     raq_14 |  0.19 | [ 0.15,  0.22] |    9.59 | &lt; .001***
raq_11     |     raq_15 |  0.20 | [ 0.16,  0.24] |   10.42 | &lt; .001***
raq_11     |     raq_16 |  0.17 | [ 0.14,  0.21] |    9.00 | &lt; .001***
raq_11     |     raq_17 |  0.47 | [ 0.43,  0.49] |   26.63 | &lt; .001***
raq_11     |     raq_18 |  0.24 | [ 0.20,  0.28] |   12.48 | &lt; .001***
raq_11     |     raq_19 |  0.19 | [ 0.16,  0.23] |   10.04 | &lt; .001***
raq_11     |     raq_20 |  0.27 | [ 0.23,  0.31] |   14.19 | &lt; .001***
raq_11     |     raq_21 |  0.29 | [ 0.25,  0.32] |   15.15 | &lt; .001***
raq_11     |     raq_22 |  0.20 | [ 0.16,  0.24] |   10.44 | &lt; .001***
raq_11     |     raq_23 |  0.13 | [ 0.09,  0.17] |    6.56 | &lt; .001***
raq_12     |     raq_13 |  0.07 | [ 0.03,  0.11] |    3.48 | 0.003**  
raq_12     |     raq_14 |  0.07 | [ 0.03,  0.11] |    3.50 | 0.003**  
raq_12     |     raq_15 |  0.07 | [ 0.03,  0.11] |    3.63 | 0.002**  
raq_12     |     raq_16 |  0.15 | [ 0.12,  0.19] |    7.87 | &lt; .001***
raq_12     |     raq_17 |  0.07 | [ 0.03,  0.11] |    3.71 | 0.002**  
raq_12     |     raq_18 |  0.10 | [ 0.06,  0.14] |    5.00 | &lt; .001***
raq_12     |     raq_19 |  0.07 | [ 0.03,  0.11] |    3.40 | 0.003**  
raq_12     |     raq_20 |  0.12 | [ 0.08,  0.16] |    6.27 | &lt; .001***
raq_12     |     raq_21 |  0.16 | [ 0.13,  0.20] |    8.42 | &lt; .001***
raq_12     |     raq_22 |  0.08 | [ 0.04,  0.12] |    4.05 | &lt; .001***
raq_12     |     raq_23 |  0.05 | [ 0.01,  0.09] |    2.70 | 0.014*   
raq_13     |     raq_14 |  0.27 | [ 0.24,  0.31] |   14.44 | &lt; .001***
raq_13     |     raq_15 |  0.29 | [ 0.25,  0.32] |   15.31 | &lt; .001***
raq_13     |     raq_16 |  0.15 | [ 0.11,  0.19] |    7.66 | &lt; .001***
raq_13     |     raq_17 |  0.18 | [ 0.14,  0.21] |    9.12 | &lt; .001***
raq_13     |     raq_18 |  0.34 | [ 0.31,  0.37] |   18.35 | &lt; .001***
raq_13     |     raq_19 |  0.26 | [ 0.22,  0.30] |   13.64 | &lt; .001***
raq_13     |     raq_20 |  0.16 | [ 0.12,  0.20] |    8.32 | &lt; .001***
raq_13     |     raq_21 |  0.17 | [ 0.14,  0.21] |    8.98 | &lt; .001***
raq_13     |     raq_22 |  0.23 | [ 0.19,  0.27] |   11.97 | &lt; .001***
raq_13     |     raq_23 |  0.14 | [ 0.10,  0.18] |    7.15 | &lt; .001***
raq_14     |     raq_15 |  0.23 | [ 0.20,  0.27] |   12.20 | &lt; .001***
raq_14     |     raq_16 |  0.08 | [ 0.05,  0.12] |    4.29 | &lt; .001***
raq_14     |     raq_17 |  0.17 | [ 0.13,  0.20] |    8.61 | &lt; .001***
raq_14     |     raq_18 |  0.26 | [ 0.22,  0.29] |   13.40 | &lt; .001***
raq_14     |     raq_19 |  0.22 | [ 0.18,  0.26] |   11.49 | &lt; .001***
raq_14     |     raq_20 |  0.15 | [ 0.11,  0.19] |    7.60 | &lt; .001***
raq_14     |     raq_21 |  0.17 | [ 0.13,  0.20] |    8.57 | &lt; .001***
raq_14     |     raq_22 |  0.22 | [ 0.18,  0.26] |   11.43 | &lt; .001***
raq_14     |     raq_23 |  0.13 | [ 0.09,  0.16] |    6.47 | &lt; .001***
raq_15     |     raq_16 |  0.11 | [ 0.07,  0.15] |    5.59 | &lt; .001***
raq_15     |     raq_17 |  0.21 | [ 0.18,  0.25] |   11.06 | &lt; .001***
raq_15     |     raq_18 |  0.32 | [ 0.29,  0.35] |   17.13 | &lt; .001***
raq_15     |     raq_19 |  0.23 | [ 0.19,  0.27] |   11.99 | &lt; .001***
raq_15     |     raq_20 |  0.16 | [ 0.12,  0.20] |    8.12 | &lt; .001***
raq_15     |     raq_21 |  0.17 | [ 0.13,  0.20] |    8.50 | &lt; .001***
raq_15     |     raq_22 |  0.24 | [ 0.20,  0.27] |   12.38 | &lt; .001***
raq_15     |     raq_23 |  0.15 | [ 0.11,  0.19] |    7.71 | &lt; .001***
raq_16     |     raq_17 |  0.18 | [ 0.14,  0.21] |    9.10 | &lt; .001***
raq_16     |     raq_18 |  0.12 | [ 0.09,  0.16] |    6.36 | &lt; .001***
raq_16     |     raq_19 |  0.14 | [ 0.10,  0.17] |    6.93 | &lt; .001***
raq_16     |     raq_20 |  0.23 | [ 0.20,  0.27] |   12.11 | &lt; .001***
raq_16     |     raq_21 |  0.26 | [ 0.23,  0.30] |   13.87 | &lt; .001***
raq_16     |     raq_22 |  0.11 | [ 0.07,  0.15] |    5.58 | &lt; .001***
raq_16     |     raq_23 |  0.10 | [ 0.06,  0.14] |    5.10 | &lt; .001***
raq_17     |     raq_18 |  0.25 | [ 0.22,  0.29] |   13.31 | &lt; .001***
raq_17     |     raq_19 |  0.20 | [ 0.16,  0.23] |   10.17 | &lt; .001***
raq_17     |     raq_20 |  0.22 | [ 0.18,  0.26] |   11.38 | &lt; .001***
raq_17     |     raq_21 |  0.26 | [ 0.22,  0.29] |   13.54 | &lt; .001***
raq_17     |     raq_22 |  0.21 | [ 0.17,  0.24] |   10.71 | &lt; .001***
raq_17     |     raq_23 |  0.14 | [ 0.10,  0.17] |    7.01 | &lt; .001***
raq_18     |     raq_19 |  0.30 | [ 0.26,  0.33] |   15.91 | &lt; .001***
raq_18     |     raq_20 |  0.18 | [ 0.14,  0.22] |    9.24 | &lt; .001***
raq_18     |     raq_21 |  0.19 | [ 0.16,  0.23] |    9.97 | &lt; .001***
raq_18     |     raq_22 |  0.27 | [ 0.23,  0.30] |   14.08 | &lt; .001***
raq_18     |     raq_23 |  0.13 | [ 0.09,  0.17] |    6.65 | &lt; .001***
raq_19     |     raq_20 |  0.16 | [ 0.13,  0.20] |    8.43 | &lt; .001***
raq_19     |     raq_21 |  0.18 | [ 0.15,  0.22] |    9.47 | &lt; .001***
raq_19     |     raq_22 |  0.42 | [ 0.39,  0.45] |   23.34 | &lt; .001***
raq_19     |     raq_23 |  0.44 | [ 0.41,  0.47] |   24.85 | &lt; .001***
raq_20     |     raq_21 |  0.35 | [ 0.31,  0.38] |   18.85 | &lt; .001***
raq_20     |     raq_22 |  0.17 | [ 0.13,  0.21] |    8.65 | &lt; .001***
raq_20     |     raq_23 |  0.11 | [ 0.08,  0.15] |    5.82 | &lt; .001***
raq_21     |     raq_22 |  0.18 | [ 0.14,  0.21] |    9.16 | &lt; .001***
raq_21     |     raq_23 |  0.14 | [ 0.10,  0.18] |    7.28 | &lt; .001***
raq_22     |     raq_23 |  0.40 | [ 0.37,  0.43] |   22.17 | &lt; .001***

p-value adjustment method: Holm (1979)
Observations: 2571</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pipe into summary() to get a condensed table of correlations:</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>correlation<span class="sc">::</span><span class="fu">correlation</span>(raq_items_tib) <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>() <span class="sc">|&gt;</span> </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">raq_23</th>
<th style="text-align: right;">raq_22</th>
<th style="text-align: right;">raq_21</th>
<th style="text-align: right;">raq_20</th>
<th style="text-align: right;">raq_19</th>
<th style="text-align: right;">raq_18</th>
<th style="text-align: right;">raq_17</th>
<th style="text-align: right;">raq_16</th>
<th style="text-align: right;">raq_15</th>
<th style="text-align: right;">raq_14</th>
<th style="text-align: right;">raq_13</th>
<th style="text-align: right;">raq_12</th>
<th style="text-align: right;">raq_11</th>
<th style="text-align: right;">raq_10</th>
<th style="text-align: right;">raq_09</th>
<th style="text-align: right;">raq_08</th>
<th style="text-align: right;">raq_07</th>
<th style="text-align: right;">raq_06</th>
<th style="text-align: right;">raq_05</th>
<th style="text-align: right;">raq_04</th>
<th style="text-align: right;">raq_03</th>
<th style="text-align: right;">raq_02</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">raq_01</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">-0.18</td>
<td style="text-align: right;">0.11</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_02</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">-0.12</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_03</td>
<td style="text-align: right;">-0.05</td>
<td style="text-align: right;">-0.12</td>
<td style="text-align: right;">-0.26</td>
<td style="text-align: right;">-0.23</td>
<td style="text-align: right;">-0.12</td>
<td style="text-align: right;">-0.15</td>
<td style="text-align: right;">-0.18</td>
<td style="text-align: right;">-0.20</td>
<td style="text-align: right;">-0.15</td>
<td style="text-align: right;">-0.09</td>
<td style="text-align: right;">-0.13</td>
<td style="text-align: right;">-0.15</td>
<td style="text-align: right;">-0.19</td>
<td style="text-align: right;">-0.10</td>
<td style="text-align: right;">-0.08</td>
<td style="text-align: right;">-0.22</td>
<td style="text-align: right;">-0.13</td>
<td style="text-align: right;">-0.17</td>
<td style="text-align: right;">-0.25</td>
<td style="text-align: right;">-0.19</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_04</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_05</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">0.37</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">0.51</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_06</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">0.51</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_07</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_08</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.55</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: right;">0.58</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_09</td>
<td style="text-align: right;">0.55</td>
<td style="text-align: right;">0.43</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_10</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_11</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_12</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_13</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_14</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_15</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_16</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_17</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_18</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_19</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_20</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_21</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_22</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>because the items use Likert scales, should use <code>polychoric()</code> function from the <code>psych</code> package</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>raq_poly <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">polychoric</span>(raq_items_tib)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>raq_poly</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: psych::polychoric(x = raq_items_tib)
Polychoric correlations 
       rq_01 rq_02 rq_03 rq_04 rq_05 rq_06 rq_07 rq_08 rq_09 rq_10 rq_11
raq_01  1.00                                                            
raq_02  0.12  1.00                                                      
raq_03 -0.20 -0.13  1.00                                                
raq_04  0.24  0.14 -0.22  1.00                                          
raq_05  0.25  0.31 -0.28  0.35  1.00                                    
raq_06  0.18  0.37 -0.18  0.26  0.57  1.00                              
raq_07  0.12  0.28 -0.14  0.18  0.40  0.50  1.00                        
raq_08  0.25  0.20 -0.24  0.28  0.40  0.38  0.28  1.00                  
raq_09  0.09  0.43 -0.09  0.11  0.18  0.22  0.18  0.18  1.00            
raq_10  0.12  0.20 -0.11  0.20  0.35  0.44  0.31  0.20  0.12  1.00      
raq_11  0.21  0.17 -0.21  0.25  0.35  0.33  0.24  0.64  0.19  0.19  1.00
raq_12  0.17  0.10 -0.16  0.21  0.21  0.13  0.10  0.14  0.07  0.08  0.11
raq_13  0.12  0.25 -0.14  0.18  0.39  0.50  0.34  0.22  0.17  0.27  0.22
raq_14  0.13  0.22 -0.10  0.16  0.30  0.39  0.28  0.25  0.14  0.24  0.20
raq_15  0.12  0.21 -0.17  0.21  0.36  0.45  0.32  0.25  0.16  0.27  0.22
raq_16  0.19  0.11 -0.22  0.30  0.27  0.18  0.13  0.23  0.09  0.14  0.19
raq_17  0.18  0.19 -0.19  0.26  0.33  0.31  0.23  0.61  0.16  0.20  0.51
raq_18  0.13  0.29 -0.17  0.19  0.42  0.56  0.39  0.31  0.16  0.32  0.27
raq_19  0.12  0.43 -0.13  0.16  0.32  0.42  0.28  0.23  0.51  0.23  0.21
raq_20  0.23  0.14 -0.26  0.32  0.38  0.25  0.16  0.29  0.11  0.20  0.30
raq_21  0.25  0.18 -0.29  0.36  0.41  0.29  0.22  0.33  0.19  0.18  0.32
raq_22  0.14  0.38 -0.13  0.17  0.30  0.36  0.25  0.25  0.48  0.17  0.22
raq_23  0.09  0.43 -0.06  0.09  0.19  0.19  0.18  0.16  0.60  0.08  0.14
       rq_12 rq_13 rq_14 rq_15 rq_16 rq_17 rq_18 rq_19 rq_20 rq_21 rq_22
raq_12  1.00                                                            
raq_13  0.08  1.00                                                      
raq_14  0.08  0.30  1.00                                                
raq_15  0.08  0.32  0.26  1.00                                          
raq_16  0.17  0.17  0.09  0.12  1.00                                    
raq_17  0.08  0.20  0.19  0.24  0.20  1.00                              
raq_18  0.11  0.38  0.28  0.35  0.14  0.28  1.00                        
raq_19  0.08  0.29  0.24  0.26  0.15  0.22  0.33  1.00                  
raq_20  0.14  0.18  0.16  0.18  0.26  0.24  0.20  0.18  1.00            
raq_21  0.18  0.19  0.18  0.18  0.29  0.29  0.21  0.20  0.39  1.00      
raq_22  0.09  0.26  0.25  0.26  0.12  0.23  0.30  0.46  0.19  0.20  1.00
raq_23  0.06  0.15  0.14  0.17  0.11  0.15  0.14  0.49  0.13  0.16  0.45
[1]  1.00

 with tau of 
          1     2       3    4
raq_01 -2.0 -0.99 -0.0229 1.01
raq_02 -2.0 -1.03  0.0532 1.03
raq_03 -2.0 -0.99 -0.0093 0.99
raq_04 -2.0 -0.99  0.0044 1.00
raq_05 -1.9 -1.00  0.0356 0.97
raq_06 -2.0 -0.99  0.0132 0.97
raq_07 -2.0 -1.01 -0.0278 0.95
raq_08 -2.0 -1.00 -0.0239 1.01
raq_09 -2.1 -1.02 -0.0288 0.97
raq_10 -2.0 -0.98  0.0307 0.97
raq_11 -2.0 -0.98 -0.0219 1.04
raq_12 -2.0 -1.04 -0.0219 1.00
raq_13 -2.0 -1.00 -0.0180 1.02
raq_14 -2.0 -1.00 -0.0424 0.95
raq_15 -2.0 -1.03 -0.0678 0.95
raq_16 -2.0 -0.99  0.0063 1.01
raq_17 -2.0 -1.02  0.0122 1.02
raq_18 -2.0 -1.03  0.0015 1.02
raq_19 -2.0 -0.98  0.0112 0.99
raq_20 -2.0 -0.99 -0.0336 0.96
raq_21 -2.1 -0.99 -0.0073 1.02
raq_22 -2.1 -1.05  0.0210 1.03
raq_23 -2.1 -1.01 -0.0015 1.01</code></pre>
</div>
</div>
<ul>
<li>matrix of correlations is stored in in a variable called <code>rho</code>, accessible with <code>raq_poly$rho</code> but we can store it in an object</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>raq_cor <span class="ot">&lt;-</span> raq_poly<span class="sc">$</span>rho</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">cor.plot</span>(raq_cor, <span class="at">upper =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>note items close to 0 - no correlation</p></li>
<li><p>note items between $+/-$0.3</p></li>
<li><p>note items greater than <span class="math inline">\(+/-\)</span> 0.9 as those may be collinear or singular</p></li>
<li><p>in this case, all questions correlate reasonably well and none are excessively large</p></li>
</ul>
</section>
</section>
<section id="bartletts-test-and-kmo-test" class="level2">
<h2 class="anchored" data-anchor-id="bartletts-test-and-kmo-test">Bartlett’s test and KMO test</h2>
<section id="bartletts-test-of-sphericity" class="level3">
<h3 class="anchored" data-anchor-id="bartletts-test-of-sphericity">Bartlett’s test of Sphericity</h3>
<ul>
<li><p>tests whether the correlation matrix is significantly different from an identity matrix (whether the correlations are all 0</p>
<ul>
<li>in FA, sample sizes are large, so the test will almost always be significant, but if it is not, then there is a problem</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">cortest.bartlett</span>(raq_cor, <span class="at">n =</span> <span class="dv">2571</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$chisq
[1] 17387.52

$p.value
[1] 0

$df
[1] 253</code></pre>
</div>
</div>
<ul>
<li>given large sample size, Bartlett’s test is highly significant, indicating there is not a significant problem</li>
</ul>
</section>
<section id="kaiser-meyer-olkin-kmo" class="level3">
<h3 class="anchored" data-anchor-id="kaiser-meyer-olkin-kmo">Kaiser-Meyer-Olkin (KMO)</h3>
<ul>
<li><p>check for sampling adequacy</p></li>
<li><p>KMO varies between 0 and 1 with 0 indicating FA is not appropriate</p></li>
<li><p>values closer to 1 indicate compact patterns of correlations and FA should reveal distinct and reliable factors</p>
<ul>
<li><p>Marvellous: values in the 0.90s</p></li>
<li><p>Meritorious: values in the 0.80s</p></li>
<li><p>Middling: values in the 0.70s</p></li>
<li><p>Mediocre: values in the 0.60s</p></li>
<li><p>Miserable: values in the 0.50s</p></li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">KMO</span>(raq_cor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Kaiser-Meyer-Olkin factor adequacy
Call: psych::KMO(r = raq_cor)
Overall MSA =  0.92
MSA for each item = 
raq_01 raq_02 raq_03 raq_04 raq_05 raq_06 raq_07 raq_08 raq_09 raq_10 raq_11 
  0.95   0.94   0.93   0.93   0.95   0.91   0.96   0.86   0.84   0.95   0.89 
raq_12 raq_13 raq_14 raq_15 raq_16 raq_17 raq_18 raq_19 raq_20 raq_21 raq_22 
  0.90   0.95   0.96   0.96   0.92   0.90   0.95   0.93   0.93   0.93   0.94 
raq_23 
  0.84 </code></pre>
</div>
</div>
<ul>
<li><p>KMO statistic (Overall MSA) is 0.92 - well above the threshold of 0.5</p></li>
<li><p>MSA for each individual item ranges from 0.84 - 0.96</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you find KMO values below 0.5, consider removing that variable, but be sure to run the KMO statistic again without the removed variable. Also run the analysis with and without the variable to compare</p>
</div>
</div>
</section>
</section>
<section id="parallel-analysis" class="level2">
<h2 class="anchored" data-anchor-id="parallel-analysis">Parallel analysis</h2>
<ul>
<li><p>to determine how many factors to extract, run <code>psych::fa.parallel()</code></p></li>
<li><p>most likely arguments</p>
<ul>
<li><p><code>n.obs() - need to tell the function the sample size (`n.obs = 2571`)</code></p></li>
<li><p><code>fm = “minres”</code> - <code>psych</code> packages uses minimum residual (minres) by default</p>
<ul>
<li>other options include principal axes (<code>pa</code>), alpha factoring (<code>alpha</code>), weighted least squares <code>wls</code>, minimum rank (<code>minrank</code>), or maximum likelihood (<code>ml</code>). Match this option to the one you’re going to use in the main factor analysis</li>
</ul></li>
<li><p><code>fa = "both"</code> - by default the function will tell the number of factors to extract, but also the number of components for PCA.</p>
<ul>
<li>can change to <code>fa = "fa</code>” to see only the number of factors to extract. It is useful to look at both methods</li>
</ul></li>
<li><p><code>use = “pairwise”</code> - by default, missing data are handled using all complete pairwise observations to calculate the correlation coefficients</p></li>
<li><p><code>cor</code> - default is the function assumes you are providing Pearson correlation coefficients, however, with ordinal variables (likert), use <code>cor = "poly"</code> (polychoric) and for binary, use tetrachoric <code>cor = "tet"</code>; with a mix of variable types, use <code>cor ="mixed"</code></p></li>
</ul></li>
</ul>
<section id="code-example" class="level3">
<h3 class="anchored" data-anchor-id="code-example">Code example</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">fa.parallel</span>(raq_items_tib, <span class="at">cor =</span> <span class="st">"poly"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Parallel analysis suggests that the number of factors =  4  and the number of components =  4 </code></pre>
</div>
</div>
<ul>
<li>or since we already stored polychoric correlations in <code>raq_cor</code>, we can just apply the function to that correlation matrix and specify the sample size</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">fa.parallel</span>(raq_cor, <span class="at">n.obs =</span> <span class="dv">2571</span>, <span class="at">fa =</span> <span class="st">"fa"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Parallel analysis suggests that the number of factors =  4  and the number of components =  NA </code></pre>
</div>
</div>
<ul>
<li><p>eigenvalues represent the size of the factor</p></li>
<li><p>factors are plotted on the x-axis with the eigenvalues on the y-axis</p></li>
<li><p>each eigenvalue is compared to an eigenvalue from a simulated data set that has no underlying factors</p>
<ul>
<li><p>essentially, we are asking if the factors are bigger than imaginary factor</p></li>
<li><p>factors that are bigger than their imaginary counterparts are retained</p></li>
</ul></li>
<li><p>eigenvalues for the observed factors are blue triangles connected by a blue line.</p></li>
<li><p>the red line shows corresponding simulated data.</p></li>
<li><p>we keep the number of factors that are above the red line, in this case, four</p></li>
</ul>
</section>
<section id="quiz" class="level3">
<h3 class="anchored" data-anchor-id="quiz">Quiz</h3>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>Based on the parallel analysis that used principal components to compute the eiegenvalues, how many factors should be extracted?</strong>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li>4</li>
</ul>
<p>Yes, fortunately this analysis agrees with the parallel analysis based on eigenvalues from factor analysis.</p>
</div>
</div>
</div>
</section>
</section>
<section id="factor-analysis" class="level2">
<h2 class="anchored" data-anchor-id="factor-analysis">Factor Analysis</h2>
<ul>
<li>we are now ready to run the FA, extracting four factors, using the <code>psych::fa()</code> function</li>
</ul>
<pre><code>my_fa_object &lt;- psych::fa(r,    
                          n.obs = 2571,  
                          nfactors = 1,  
                          fm = "minres", 
                          rotate = "oblimin", 
                          scores = "regression", 
                          max.iter = 50, 
                          use = "pairwise", 
                          cor = "cor" 
                          )</code></pre>
<ul>
<li><code>r</code> -&gt; the data being fed into the function (<code>raq_items_tib</code> or <code>raq_cor</code>)</li>
<li><code>n.obs = 2571</code> as with parallel analysis, if we run the FA from the correlation matrix instead of the raw data, we must tell the function the sample size</li>
<li><code>nfactors = 1</code> the number of factors to extract (default is 1)</li>
<li><code>fm = "minres"</code> method of factor analysis, typically leave the default</li>
<li><code>rotate = "oblimin"</code> method of factor rotation</li>
<li><code>scores = "regression"</code> method of computing factor scores. because we should use oblique rotation, change this argument to <code>scores = "tenBerge"</code></li>
<li><code>max.iter = 50</code> number of iterations. If you get a n error message about convergence, increase this number</li>
<li><code>use = "pairwise"</code> determines how missing values are treated, default is fine</li>
<li><code>cor = "cor"</code> same as defined for <code>fa.parallel()</code></li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Factor rotation
</div>
</div>
<div class="callout-body-container callout-body">
<p>factor rotation requires <code>GPArotation</code> package loaded</p>
</div>
</div>
<section id="code-example-1" class="level3">
<h3 class="anchored" data-anchor-id="code-example-1">Code Example</h3>
<ul>
<li>as with parallel analysis we can either feed the raw data into the function remembering to set <code>cor = "poly"</code> so the analysis is based on polychoric correlations</li>
<li>or we can feed in the correlation matrix and sample size</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>raq_fa <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">fa</span>(raq_items_tib, </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">nfactors =</span> <span class="dv">4</span>, </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">scores =</span> <span class="st">"tenBerge"</span>, </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">cor =</span> <span class="st">"poly"</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  raq_fa </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Factor Analysis using method =  minres
Call: psych::fa(r = raq_items_tib, nfactors = 4, scores = "tenBerge", 
    cor = "poly")
Standardized loadings (pattern matrix) based upon correlation matrix
         MR1   MR2   MR4   MR3   h2   u2 com
raq_01 -0.03  0.01  0.39  0.06 0.17 0.83 1.1
raq_02  0.25  0.48  0.02 -0.03 0.38 0.62 1.5
raq_03  0.00  0.01 -0.43 -0.03 0.20 0.80 1.0
raq_04  0.03 -0.02  0.56  0.00 0.33 0.67 1.0
raq_05  0.45 -0.01  0.39  0.02 0.54 0.46 2.0
raq_06  0.84  0.00 -0.01  0.03 0.73 0.27 1.0
raq_07  0.56  0.04  0.00  0.04 0.35 0.65 1.0
raq_08  0.00 -0.01 -0.01  0.88 0.75 0.25 1.0
raq_09 -0.07  0.81  0.00  0.03 0.62 0.38 1.0
raq_10  0.49 -0.05  0.09 -0.02 0.26 0.74 1.1
raq_11 -0.01  0.01  0.03  0.72 0.55 0.45 1.0
raq_12 -0.01  0.01  0.37 -0.07 0.11 0.89 1.1
raq_13  0.57  0.03  0.04 -0.03 0.34 0.66 1.0
raq_14  0.42  0.04  0.01  0.06 0.22 0.78 1.1
raq_15  0.48  0.03  0.03  0.05 0.29 0.71 1.0
raq_16 -0.05  0.02  0.51 -0.01 0.23 0.77 1.0
raq_17  0.03  0.02  0.00  0.68 0.49 0.51 1.0
raq_18  0.63  0.01 -0.02  0.07 0.43 0.57 1.0
raq_19  0.26  0.56  0.00 -0.01 0.50 0.50 1.4
raq_20  0.00  0.01  0.54  0.05 0.32 0.68 1.0
raq_21 -0.02  0.05  0.59  0.06 0.40 0.60 1.0
raq_22  0.19  0.52  0.03  0.05 0.41 0.59 1.3
raq_23 -0.08  0.79  0.02 -0.01 0.59 0.41 1.0

                       MR1  MR2  MR4  MR3
SS loadings           3.04 2.24 2.03 1.91
Proportion Var        0.13 0.10 0.09 0.08
Cumulative Var        0.13 0.23 0.32 0.40
Proportion Explained  0.33 0.24 0.22 0.21
Cumulative Proportion 0.33 0.57 0.79 1.00

 With factor correlations of 
     MR1  MR2  MR4  MR3
MR1 1.00 0.38 0.50 0.48
MR2 0.38 1.00 0.28 0.28
MR4 0.50 0.28 1.00 0.57
MR3 0.48 0.28 0.57 1.00

Mean item complexity =  1.1
Test of the hypothesis that 4 factors are sufficient.

df null model =  253  with the objective function =  6.79 with Chi Square =  17387.52
df of  the model are 167  and the objective function was  0.1 

The root mean square of the residuals (RMSR) is  0.01 
The df corrected root mean square of the residuals is  0.02 

The harmonic n.obs is  2571 with the empirical chi square  205.03  with prob &lt;  0.024 
The total n.obs was  2571  with Likelihood Chi Square =  267.21  with prob &lt;  1.3e-06 

Tucker Lewis Index of factoring reliability =  0.991
RMSEA index =  0.015  and the 90 % confidence intervals are  0.012 0.019
BIC =  -1044.08
Fit based upon off diagonal values = 1
Measures of factor score adequacy             
                                                   MR1  MR2  MR4  MR3
Correlation of (regression) scores with factors   0.93 0.91 0.88 0.92
Multiple R square of scores with factors          0.87 0.83 0.77 0.85
Minimum correlation of possible factor scores     0.73 0.66 0.54 0.70</code></pre>
</div>
</div>
<ul>
<li>factors are labeled <code>MR1</code>, <code>MR2</code>, <code>MR3</code>, and <code>MR4</code></li>
<li>below the pattern matrix is information about how much variance each factor accounts for
<ul>
<li><code>Proportion var</code> - <code>MR1</code> accounts for 0.13 of the overall variance (13%), etc</li>
<li><code>Cumulative var</code> is the proportion of the variance explained cumulatively by the factors - <code>MR1</code> accounts for 0.13 and <code>MR1</code> + <code>MR2</code> together account for 0.13 + 0.10 = 0.23 (23%)
<ul>
<li>all four together account for 0.40 (40%)</li>
</ul></li>
<li><code>Proportion explained</code> is the proportion of the explained variance that is explained by a factor, so of the 40% of the variiance accounted for, 0.33 (33%) is attributable to <code>MR1</code></li>
</ul></li>
<li>next, correlations between factors are displayed
<ul>
<li>all are non-zero, indicating the factors are correlated (and oblique rotation was appropriate)</li>
<li>all factors are positively and fairly strongly correlated to teach other meaning the latent constructs represented by the factors are related.</li>
</ul></li>
<li>several fit indices that tell us how the model fits the data
<ul>
<li>chi-square statistic for the model is given as the <code>likelihood chi square</code>, <span class="math inline">\(X^2=267.21, p&lt;0.001\)</span>
<ul>
<li>we want this to be non-significant but ours is highly significant. Our sample size is 2571 so small deviations from a good fit will be significant. This highlights the limitation of using significance to indicate model fit.</li>
<li>the Tucker Lewis Index of factoring reliability (TLI) is given as 0.991</li>
<li>RMSEA is 0.015 90% CI[0.012, 0.019]</li>
<li>RMSR is 0.01</li>
</ul></li>
</ul></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Fit Indices
</div>
</div>
<div class="callout-body-container callout-body">
<p>Good fit is (probably) indicated by</p>
<ul>
<li>combination of TLI &gt; 0.96, and SRMR (RMSR in the output) &lt; 0.06</li>
<li>combination of RMSEA &lt; 0.05 and SRMR &lt; 0.09</li>
</ul>
<p>The TLI is 0.99, which is greater than 0.96, and RMSR is 0.01 which is smaller than both 0.09 and 0.06. Furthermore, RMSEA is 0.015, which is less than 0.05. With the caveat that universal cut-offs need to be taken with a pinch of salt, it’s reasonable to conclude that the model has excellent fit.</p>
</div>
</div>
</section>
<section id="interpreting-fa" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-fa">Interpreting FA</h3>
<ul>
<li>look at factor loadings (top of output in the pattern matrix) for each question on each factor to see which items load most heavily onto which factors</li>
<li>this is difficult to interpret in the raw form, so use <code>parameters::model_parameters()</code> to sort items by their factor loadings and suppress factor loading sbelow a certain value</li>
</ul>
<p>General form</p>
<pre><code>parameters::model_parameters(my_fa_object, sort = TRUE, threshold = "max")</code></pre>
<ul>
<li><code>my_fa_object</code> is the factor analysis object containing the factor loadings.</li>
<li><code>sort = "TRUE"</code> sorts items by their factor loadings</li>
<li>set <code>threshold</code> to a value above which we will show values. Default is maximum loading. To see all factor loadings, set <code>threshold = NULL</code></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>parameters<span class="sc">::</span><span class="fu">model_parameters</span>(raq_fa, <span class="at">sort =</span> <span class="cn">TRUE</span>, <span class="at">threshold =</span> <span class="st">"0.2"</span>) <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">MR1</th>
<th style="text-align: right;">MR2</th>
<th style="text-align: right;">MR4</th>
<th style="text-align: right;">MR3</th>
<th style="text-align: right;">Complexity</th>
<th style="text-align: right;">Uniqueness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">raq_06</td>
<td style="text-align: right;">0.84</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">-0.01</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.27</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_18</td>
<td style="text-align: right;">0.63</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">-0.02</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">1.03</td>
<td style="text-align: right;">0.57</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_13</td>
<td style="text-align: right;">0.57</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">-0.03</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">0.66</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_07</td>
<td style="text-align: right;">0.56</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">0.65</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_10</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: right;">-0.05</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">-0.02</td>
<td style="text-align: right;">1.08</td>
<td style="text-align: right;">0.74</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_15</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">1.04</td>
<td style="text-align: right;">0.71</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_05</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">-0.01</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">1.97</td>
<td style="text-align: right;">0.46</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_14</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">1.06</td>
<td style="text-align: right;">0.78</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_09</td>
<td style="text-align: right;">-0.07</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">0.38</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_23</td>
<td style="text-align: right;">-0.08</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">-0.01</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">0.41</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_19</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">0.56</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">-0.01</td>
<td style="text-align: right;">1.41</td>
<td style="text-align: right;">0.50</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_22</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">0.52</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">1.29</td>
<td style="text-align: right;">0.59</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_02</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">-0.03</td>
<td style="text-align: right;">1.54</td>
<td style="text-align: right;">0.62</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_21</td>
<td style="text-align: right;">-0.02</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">1.04</td>
<td style="text-align: right;">0.60</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_04</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">-0.02</td>
<td style="text-align: right;">0.56</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">0.67</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_20</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.54</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">0.68</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_16</td>
<td style="text-align: right;">-0.05</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.51</td>
<td style="text-align: right;">-0.01</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">0.77</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_03</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">-0.43</td>
<td style="text-align: right;">-0.03</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">0.80</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_01</td>
<td style="text-align: right;">-0.03</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">1.06</td>
<td style="text-align: right;">0.83</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_12</td>
<td style="text-align: right;">-0.01</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.37</td>
<td style="text-align: right;">-0.07</td>
<td style="text-align: right;">1.07</td>
<td style="text-align: right;">0.89</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_08</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">-0.01</td>
<td style="text-align: right;">-0.01</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">raq_11</td>
<td style="text-align: right;">-0.01</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.45</td>
</tr>
<tr class="odd">
<td style="text-align: left;">raq_17</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.51</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>Now we can see patterns in the questions that load onto the same factors</li>
<li>Items that load highly on <code>MR1</code> seem to be items that relate to fear of computers
<ul>
<li>raq_05: I don’t understand statistics (also loads highly onto <code>MR4</code>)</li>
<li>raq_06: I have little experience of computers</li>
<li>raq_07: All computers hate me</li>
<li>raq_10: Computers are useful only for playing games</li>
<li>raq_13: I worry that I will cause irreparable damage because of my incompetence with computers</li>
<li>raq_14: Computers have minds of their own and deliberately go wrong whenever I use them</li>
<li>raq_15: Computers are out to get me</li>
<li>raq_18: R always crashes when I try to use it</li>
</ul></li>
<li>Items that load onto <code>MR2</code> relate to fear of peer/social evaluation
<ul>
<li>raq_02: My friends will think I’m stupid for not being able to cope with R</li>
<li>raq_09: My friends are better at statistics than me</li>
<li>raq_19: Everybody looks at me when I use R</li>
<li>raq_22: My friends are better at R than I am</li>
<li>raq_23: If I am good at statistics people will think I am a nerd</li>
</ul></li>
<li>Questions that load onto <code>MR4</code> relate to fear of statistics
<ul>
<li>raq_01: Statistics make me cry</li>
<li>raq_03: Standard deviations excite me</li>
<li>raq_04: I dream that Pearson is attacking me with correlation coefficients</li>
<li>raq_05: I don’t understand statistics</li>
<li>raq_12: People try to tell you that R makes statistics easier to understand but it doesn’t</li>
<li>raq_16: I weep openly at the mention of central tendency</li>
<li>raq_20: I can’t sleep for thoughts of eigenvectors</li>
<li>raq_21: I wake up under my duvet thinking that I am trapped under a normal distribution</li>
</ul></li>
<li>questions that load onto <code>MR3</code> relate to fear of math
<ul>
<li>raq_08: I have never been good at mathematics</li>
<li>raq_11: I did badly at mathematics at school</li>
<li>raq_17: I slip into a coma whenever I see an equation</li>
</ul></li>
</ul>
<p>Analysis seems to reveal that the questionnaire is composed of four subscales: fear of statistics, fear of computers, fear of maths, fear of negative peer evaluation.</p>
<ul>
<li>two possibilities:
<ul>
<li>the RAQ failed to measure what it set out to measure -&gt; R anxiety but instead measures related constructs</li>
<li>these four constructs are subcomponents of R anxiety</li>
</ul></li>
<li>However, the factor analysis does not indicate which of these is true.</li>
</ul>
</section>
</section>
<section id="reliability-analysis" class="level2">
<h2 class="anchored" data-anchor-id="reliability-analysis">Reliability Analysis</h2>
<section id="mcdonalds-omega_t-and-omega_h" class="level3">
<h3 class="anchored" data-anchor-id="mcdonalds-omega_t-and-omega_h">McDonald’s <span class="math inline">\(\omega_t\)</span> and <span class="math inline">\(\omega_h\)</span></h3>
<ul>
<li>if items are all scored in the same direction, we can select the variables on a particular subscale and pipe them into <code>omega()</code> functions in the <code>psych</code> package</li>
</ul>
<pre><code>my_omg &lt;- psych::omega(
    my_tibble
    nfactors = 1,
    fm = "minres",
    key = c(1, 1, -1, 1, 1 … 1),
    rotate = "oblimin",
    poly = FALSE
  )</code></pre>
<dl>
<dt><code>my_omg</code></dt>
<dd>
<p>name to give the object that stores the results</p>
</dd>
<dt><code>my_tibble</code></dt>
<dd>
<p>name of the tibble containing your data</p>
</dd>
</dl>
</section>
<section id="code-example-2" class="level3">
<h3 class="anchored" data-anchor-id="code-example-2">Code Example</h3>
<ul>
<li>need to recreate the original FA</li>
<li>arguments will be the same as they were set for the fa</li>
<li>the <code>key</code> argument allows us to reverse item scoring on the fly</li>
<li>supply the key argument with a vector of 1s and -1s that is the same length as the number of variables being fed into the <code>omega()</code> function</li>
<li>for RAQ, we have 23 items with the third being reverse coded</li>
<li>entering the items in order into <code>omega()</code> gives</li>
</ul>
<pre><code>key = c(1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)</code></pre>
<p>or</p>
<pre><code>key = c(1, 1, -1, rep(1, 20))</code></pre>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>raq_omg <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">omega</span>(raq_items_tib,</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">nfactors =</span> <span class="dv">4</span>,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">fm =</span> <span class="st">"minres"</span>,</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">key =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">20</span>)),</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">poly =</span> <span class="cn">TRUE</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>                        )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>raq_omg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Omega 
Call: omegah(m = m, nfactors = nfactors, fm = fm, key = key, flip = flip, 
    digits = digits, title = title, sl = sl, labels = labels, 
    plot = plot, n.obs = n.obs, rotate = rotate, Phi = Phi, option = option, 
    covar = covar)
Alpha:                 0.88 
G.6:                   0.89 
Omega Hierarchical:    0.68 
Omega H asymptotic:    0.75 
Omega Total            0.9 

Schmid Leiman Factor loadings greater than  0.2 
           g   F1*   F2*   F3*   F4*    h2   h2   u2   p2  com
raq_01  0.32              0.26             0.17 0.83 0.57 1.99
raq_02  0.37        0.43              0.38 0.38 0.62 0.37 2.34
raq_03- 0.34              0.29        0.20 0.20 0.80 0.56 1.97
raq_04  0.43              0.38        0.33 0.33 0.67 0.56 1.98
raq_05  0.62  0.32        0.27        0.54 0.54 0.46 0.70 1.90
raq_06  0.61  0.60                    0.73 0.73 0.27 0.51 2.00
raq_07  0.44  0.39                    0.35 0.35 0.65 0.54 2.00
raq_08  0.62                    0.61  0.75 0.75 0.25 0.51 2.00
raq_09  0.32        0.73              0.62 0.62 0.38 0.17 1.39
raq_10  0.37  0.35                    0.26 0.26 0.74 0.53 2.07
raq_11  0.54                    0.50  0.55 0.55 0.45 0.54 1.99
raq_12  0.22              0.25             0.11 0.89 0.44 2.05
raq_13  0.42  0.40                    0.34 0.34 0.66 0.51 2.02
raq_14  0.36  0.30                    0.22 0.22 0.78 0.59 1.98
raq_15  0.41  0.34                    0.29 0.29 0.71 0.59 1.97
raq_16  0.34              0.34        0.23 0.23 0.77 0.49 2.02
raq_17  0.52                    0.47  0.49 0.49 0.51 0.55 1.99
raq_18  0.48  0.44                    0.43 0.43 0.57 0.54 2.02
raq_19  0.43        0.51              0.50 0.50 0.50 0.37 2.23
raq_20  0.43              0.36        0.32 0.32 0.68 0.58 1.95
raq_21  0.49              0.40        0.40 0.40 0.60 0.59 1.97
raq_22  0.41        0.46              0.41 0.41 0.59 0.41 2.16
raq_23  0.30        0.71              0.59 0.59 0.41 0.15 1.35

With Sums of squares  of:
   g  F1*  F2*  F3*  F4*   h2 
4.40 1.39 1.71 0.85 0.86 4.37 

general/max  1.01   max/min =   5.15
mean percent general =  0.49    with sd =  0.13 and cv of  0.26 
Explained Common Variance of the general factor =  0.48 

The degrees of freedom are 167  and the fit is  0.1 
The number of observations was  2571  with Chi Square =  267.21  with prob &lt;  1.3e-06
The root mean square of the residuals is  0.01 
The df corrected root mean square of the residuals is  0.02
RMSEA index =  0.015  and the 90 % confidence intervals are  0.012 0.019
BIC =  -1044.08

Compare this with the adequacy of just a general factor and no group factors
The degrees of freedom for just the general factor are 230  and the fit is  2.39 
The number of observations was  2571  with Chi Square =  6122.42  with prob &lt;  0
The root mean square of the residuals is  0.1 
The df corrected root mean square of the residuals is  0.11 

RMSEA index =  0.1  and the 90 % confidence intervals are  0.098 0.102
BIC =  4316.45 

Measures of factor score adequacy             
                                                 g  F1*  F2*   F3*  F4*
Correlation of scores with factors            0.84 0.76 0.87  0.67 0.74
Multiple R square of scores with factors      0.71 0.57 0.75  0.44 0.55
Minimum correlation of factor score estimates 0.42 0.14 0.51 -0.11 0.10

 Total, General and Subset omega for each subset
                                                 g  F1*  F2*  F3*  F4*
Omega total for total scores and subscales    0.90 0.83 0.80 0.69 0.81
Omega general for total scores and subscales  0.68 0.48 0.23 0.38 0.43
Omega group for total scores and subscales    0.18 0.35 0.56 0.31 0.38</code></pre>
</div>
</div>
<ul>
<li><p>note the table of factor loadings and that <code>raq_03-</code> is labeled with a minus to indicate it is reverse coded</p></li>
<li><p>column labeled <code>g</code>shows the loading of each item on the general factor</p>
<ul>
<li>if any items load poorly, then a common factor model isn’t appropriate</li>
<li>all items here have a factor loading far enough from zero that a general factor model is appropriate</li>
</ul></li>
<li><p>Columns F1-F4 show the loadings of each item on the four factors we extracted</p>
<ul>
<li>these values differ from the original factor analysis because this one includes a general factor</li>
<li>the patterns of item loadings to factors follow the same pattern as the original FA</li>
</ul></li>
<li><p>at the top of the text output are reliability estimates for the general factor, including</p>
<ul>
<li>Chronbach’s <span class="math inline">\(\alpha=0.88\)</span></li>
<li><span class="math inline">\(\omega_h=0.68\)</span></li>
<li><span class="math inline">\(\omega_t=0.9\)</span></li>
</ul></li>
<li><p><span class="math inline">\(\omega_h\)</span> is a measure of how much the items reflect a single construct, and a value of 0.68 suggests they do but there is still a lot of unexplained variance in the general factor</p></li>
<li><p>further down in the output, we see that only 48% of the variance in the common factor is explained by the items</p></li>
<li><p><span class="math inline">\(\omega_t\)</span> is the total reliability and 0.90 is high, suggesting scores are reliable</p></li>
<li><p>next are two sets of model fit stats</p></li>
<li><p>the first set are for the model that has four factors and repeat the nformation from the original EFA</p>
<ul>
<li><code>chi-square</code> is significant, <span class="math inline">\(X^2= 267.21, p&lt;0.001\)</span>, which is a bad thing but unsurprising given the sample size</li>
<li><code>RMSR = 0.01</code></li>
<li><code>RMSEA = 0.02 90% CI[0.01-0.02]</code></li>
</ul></li>
<li><p>Next is the same information but for the model that contains only the general factor and not the four sub-factors</p>
<ul>
<li>the fit gets worse as shown by
<ul>
<li>larger and more significant <code>chi-square, $X^2=6122.42, p&lt;0.001$</code></li>
<li>larger <code>RMSR=0.10</code></li>
<li>larger <code>RMSEA=0.1090% CI[0.10, 0.10]</code></li>
</ul></li>
</ul></li>
<li><p>all this tells us that the model that characterizes the RAQ in terms of four factors is a better fit of the data than a model that characterises it as a single factor</p></li>
<li><p>finally, under the Total, General, and Subset omega for each subset, we get the <span class="math inline">\(\omega_t\)</span> (labeled omega total) and <span class="math inline">\(\omega_h\)</span> (labeled omega general) for the general factor (column <code>g</code>) and for the subfactors.</p></li>
<li><p>values for the general factor repeat the information at tht e start of the output</p></li>
<li><p>the values for the subfactors are particularly relvant for <span class="math inline">\(\omega_t\)</span> because it represents the total reliability of the scores, so these values tell us the total reliability of the scores from the underlying subscales</p>
<ul>
<li>for anxiety related to computers (F1) we have <span class="math inline">\(\omega_t=0.83\)</span></li>
<li>anxiety around peer or social evaluation (F2) $_t=0.80</li>
<li>anxiety around statistics (F3) <span class="math inline">\(\omega_t=0.69\)</span></li>
<li>anxiety around maths (F4) <span class="math inline">\(\omega_t=0.81\)</span></li>
</ul></li>
<li><p>scores from ach subscale are reliable, although somewhat less so for anxiety around statistics</p></li>
</ul>
</section>
</section>
<section id="cronbachs-alpha" class="level2">
<h2 class="anchored" data-anchor-id="cronbachs-alpha">Cronbach’s <span class="math inline">\(\alpha\)</span></h2>
<ul>
<li>Lots of reasons not to use Cronbach’s <span class="math inline">\(\alpha\)</span> (see the book for details)</li>
<li>if Cronbach’s <span class="math inline">\(\alpha\)</span> is needed, it must be computed on the individual subscales
<ul>
<li>Anxiety related to computers: raq_06, raq_07, raq_10, raq_13, raq_14, raq_15 and raq_18</li>
<li>Anxiety around peer or social evaluation: raq_02, raq_09, raq_19, raq_22, and raq_2</li>
<li>Anxiety around statistics: raq_01, raq_03 (reverse scored), raq_04, raq_05, raq_12, raq_16, raq_20, and raq_21</li>
<li>Anxiety around maths: raq_08, raq_11 and raq_17</li>
</ul></li>
<li>pipe the variables for each subscale into <code>psych::alpha()</code> function</li>
</ul>
<section id="code-example-for-fear-of-computers" class="level3">
<h3 class="anchored" data-anchor-id="code-example-for-fear-of-computers">Code example for <code>fear of computers</code></h3>
<ul>
<li>example excludes <code>raq_05</code>, which makes more sense on the fear of statistics factor [<a href="https://github.com/profandyfield/discovr/issues/19">See github issue</a>]</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>raq_tib <span class="sc">|&gt;</span> </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(raq_06, raq_07, raq_10, raq_13, raq_14, raq_15, raq_18) <span class="sc">|&gt;</span> </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  psych<span class="sc">::</span><span class="fu">alpha</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = dplyr::select(raq_tib, raq_06, raq_07, raq_10, 
    raq_13, raq_14, raq_15, raq_18))

  raw_alpha std.alpha G6(smc) average_r S/N    ase mean   sd median_r
      0.77      0.77    0.75      0.32 3.3 0.0069  3.5 0.64     0.29

    95% confidence boundaries 
         lower alpha upper
Feldt     0.75  0.77  0.78
Duhachek  0.76  0.77  0.78

 Reliability if an item is dropped:
       raw_alpha std.alpha G6(smc) average_r S/N alpha se  var.r med.r
raq_06      0.70      0.70    0.66      0.28 2.3   0.0092 0.0015  0.28
raq_07      0.74      0.74    0.71      0.32 2.9   0.0079 0.0075  0.29
raq_10      0.75      0.75    0.73      0.34 3.1   0.0075 0.0068  0.32
raq_13      0.74      0.74    0.71      0.32 2.9   0.0079 0.0074  0.29
raq_14      0.76      0.76    0.73      0.35 3.2   0.0073 0.0065  0.32
raq_15      0.75      0.75    0.72      0.33 3.0   0.0076 0.0076  0.31
raq_18      0.73      0.73    0.70      0.31 2.7   0.0082 0.0063  0.29

 Item statistics 
          n raw.r std.r r.cor r.drop mean   sd
raq_06 2571  0.79  0.79  0.77   0.68  3.5 0.99
raq_07 2571  0.65  0.65  0.56   0.49  3.5 1.00
raq_10 2571  0.59  0.59  0.48   0.42  3.5 1.00
raq_13 2571  0.64  0.64  0.55   0.48  3.5 0.98
raq_14 2571  0.57  0.57  0.45   0.39  3.5 1.00
raq_15 2571  0.61  0.61  0.51   0.44  3.5 0.99
raq_18 2571  0.67  0.68  0.60   0.53  3.5 0.97

Non missing response frequency for each item
          1    2    3    4    5 miss
raq_06 0.02 0.14 0.35 0.33 0.17    0
raq_07 0.02 0.13 0.33 0.34 0.17    0
raq_10 0.02 0.14 0.35 0.32 0.17    0
raq_13 0.02 0.14 0.33 0.35 0.15    0
raq_14 0.02 0.13 0.33 0.35 0.17    0
raq_15 0.02 0.13 0.32 0.35 0.17    0
raq_18 0.02 0.13 0.35 0.35 0.15    0</code></pre>
</div>
</div>
<ul>
<li><p>value at the top is Cronbach’s <span class="math inline">\(\alpha\)</span>, with the 95% CI below.</p></li>
<li><p>looking for between 0.70 and 0.80, in this case Cronbach’s <span class="math inline">\(\alpha\)</span>=0.77 [0.75, 0.78] indicating good reliability</p></li>
<li><p>next is a table of statistics for the scale if we deleted each item in turn</p></li>
<li><p>the values in the column <code>raw_alpha</code> are the values of the overall <span class="math inline">\(\alpha\)</span></p></li>
<li><p>we are looking for a change in Cronbach’s <span class="math inline">\(\alpha\)</span> (0.77)</p>
<ul>
<li>if values are greater than 0.77, then reliability would have improved if the item were removed - not the case here</li>
</ul></li>
<li><p>the table labeled <code>item statistics</code> shows, in <code>raw.r</code>, the correlations between each item and the total score from the scale - <code>item-total correlations</code></p>
<ul>
<li>there is a problem with this statistic in that the item is included in the scale total, which inflates the overall correlation.</li>
<li>we want these correlations to be computed without the item in question, and these values are in <code>r.drop</code></li>
<li>in a reliable scale all items should correlate with the total, so we’re looking for items that don’t correlate with the overall score from the subscale. If any values of <code>r.drop</code> are elss than 0.3, we have problems becasuse that means an item does not correlate well with the subscale
<ul>
<li>0.3 is ‘reasonable’ - use your judgement</li>
</ul></li>
</ul></li>
<li><p>the final table tells us what percentage of people gave each response to each of the items, which is useful to make sure everyone in the sample is not giving the same response.</p>
<ul>
<li>usually, if everyone gives the same response, the item will have poor reliability statistics</li>
<li>for this subscale, few people responded with a 1 on any of the items suggesting that no one is feeling the love for computers or that the items are doing a poor job of eliciting those extreme responses</li>
</ul></li>
</ul>
</section>
<section id="code-example-for-fear-of-peersocial-evaluation" class="level3">
<h3 class="anchored" data-anchor-id="code-example-for-fear-of-peersocial-evaluation">Code example for <code>fear of peer/social evaluation</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>raq_tib <span class="sc">|&gt;</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(raq_02, raq_09, raq_19, raq_22, raq_23)  <span class="sc">|&gt;</span> </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  psych<span class="sc">::</span><span class="fu">alpha</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = dplyr::select(raq_tib, raq_02, raq_09, raq_19, 
    raq_22, raq_23))

  raw_alpha std.alpha G6(smc) average_r S/N    ase mean   sd median_r
      0.78      0.78    0.75      0.42 3.6 0.0067  3.5 0.72     0.41

    95% confidence boundaries 
         lower alpha upper
Feldt     0.77  0.78   0.8
Duhachek  0.77  0.78   0.8

 Reliability if an item is dropped:
       raw_alpha std.alpha G6(smc) average_r S/N alpha se  var.r med.r
raq_02      0.77      0.77    0.71      0.45 3.3   0.0075 0.0027  0.43
raq_09      0.72      0.72    0.67      0.40 2.6   0.0089 0.0011  0.40
raq_19      0.74      0.74    0.69      0.42 2.8   0.0084 0.0049  0.40
raq_22      0.76      0.76    0.71      0.44 3.1   0.0078 0.0038  0.42
raq_23      0.73      0.73    0.67      0.41 2.7   0.0086 0.0018  0.40

 Item statistics 
          n raw.r std.r r.cor r.drop mean   sd
raq_02 2571  0.68  0.69  0.55   0.49  3.5 0.97
raq_09 2571  0.77  0.77  0.70   0.62  3.5 0.99
raq_19 2571  0.74  0.74  0.64   0.57  3.5 1.00
raq_22 2571  0.70  0.71  0.59   0.52  3.5 0.96
raq_23 2571  0.76  0.76  0.68   0.60  3.5 0.98

Non missing response frequency for each item
          1    2    3    4    5 miss
raq_02 0.02 0.13 0.37 0.33 0.15    0
raq_09 0.02 0.13 0.33 0.34 0.17    0
raq_19 0.02 0.14 0.34 0.34 0.16    0
raq_22 0.02 0.13 0.36 0.34 0.15    0
raq_23 0.02 0.14 0.34 0.34 0.16    0</code></pre>
</div>
</div>
<ul>
<li>good overall reliability (<span class="math inline">\(\alpha=0.78 [o.77, 0.80]\)</span>)</li>
<li>no items improve the value if they are dropped</li>
<li>item correlations with the total are all good</li>
<li>again we have issues with the items not eliciting extremely low responses</li>
</ul>
</section>
<section id="code-example-for-fear-of-maths" class="level3">
<h3 class="anchored" data-anchor-id="code-example-for-fear-of-maths">Code example for <code>fear of maths</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>raq_tib <span class="sc">|&gt;</span> </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(raq_08, raq_11, raq_17)  <span class="sc">|&gt;</span> </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  psych<span class="sc">::</span><span class="fu">alpha</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = dplyr::select(raq_tib, raq_08, raq_11, raq_17))

  raw_alpha std.alpha G6(smc) average_r S/N    ase mean   sd median_r
      0.77      0.77     0.7      0.53 3.4 0.0078  3.5 0.81     0.55

    95% confidence boundaries 
         lower alpha upper
Feldt     0.76  0.77  0.79
Duhachek  0.76  0.77  0.79

 Reliability if an item is dropped:
       raw_alpha std.alpha G6(smc) average_r S/N alpha se var.r med.r
raq_08      0.63      0.63    0.47      0.47 1.7    0.014    NA  0.47
raq_11      0.71      0.71    0.55      0.55 2.4    0.012    NA  0.55
raq_17      0.74      0.74    0.58      0.58 2.8    0.010    NA  0.58

 Item statistics 
          n raw.r std.r r.cor r.drop mean   sd
raq_08 2571  0.86  0.86  0.75   0.66  3.5 0.98
raq_11 2571  0.82  0.82  0.68   0.60  3.5 0.99
raq_17 2571  0.81  0.81  0.65   0.57  3.5 0.97

Non missing response frequency for each item
          1    2    3    4    5 miss
raq_08 0.02 0.14 0.33 0.35 0.16    0
raq_11 0.02 0.14 0.33 0.36 0.15    0
raq_17 0.02 0.13 0.35 0.34 0.15    0</code></pre>
</div>
</div>
<ul>
<li>fairly high reliability (<span class="math inline">\(\alpha=0.77 [0.76, 0.79]\)</span>)</li>
<li>no items improve value if they are dropped</li>
<li>item correlations with the total subscale are all good</li>
<li>still issues with items not eliciting low responses</li>
</ul>
</section>
<section id="code-example-for-fear-of-statistics" class="level3">
<h3 class="anchored" data-anchor-id="code-example-for-fear-of-statistics">Code example for <code>fear of statistics</code></h3>
<ul>
<li>the <code>fear of statistics</code> subscale contains <code>raq_3</code>, which is reverse scored so we need to include the <code>keys</code> argument within the function</li>
<li>note that in the <code>omega()</code> function, the argument is <code>key</code>, but in the <code>alpha()</code> function, the argument is <code>keys</code></li>
<li></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>raq_tib <span class="sc">|&gt;</span> </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(raq_01, raq_03, raq_04, raq_05, raq_12, raq_16, raq_20, raq_21)  <span class="sc">|&gt;</span> </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  psych<span class="sc">::</span><span class="fu">alpha</span>(<span class="at">keys =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = dplyr::select(raq_tib, raq_01, raq_03, raq_04, 
    raq_05, raq_12, raq_16, raq_20, raq_21), keys = c(1, -1, 
    1, 1, 1, 1, 1, 1))

  raw_alpha std.alpha G6(smc) average_r S/N    ase mean   sd median_r
      0.71      0.71    0.68      0.23 2.4 0.0087  3.4 0.57     0.22

    95% confidence boundaries 
         lower alpha upper
Feldt     0.69  0.71  0.72
Duhachek  0.69  0.71  0.72

 Reliability if an item is dropped:
        raw_alpha std.alpha G6(smc) average_r S/N alpha se  var.r med.r
raq_01       0.69      0.69    0.67      0.24 2.2   0.0092 0.0050  0.24
raq_03-      0.69      0.69    0.66      0.24 2.2   0.0094 0.0051  0.23
raq_04       0.67      0.67    0.64      0.22 2.0   0.0100 0.0046  0.22
raq_05       0.66      0.66    0.63      0.22 1.9   0.0102 0.0035  0.21
raq_12       0.71      0.71    0.68      0.26 2.4   0.0088 0.0032  0.24
raq_16       0.68      0.68    0.66      0.24 2.2   0.0095 0.0051  0.22
raq_20       0.67      0.67    0.64      0.22 2.0   0.0099 0.0037  0.22
raq_21       0.66      0.66    0.63      0.22 1.9   0.0103 0.0032  0.21

 Item statistics 
           n raw.r std.r r.cor r.drop mean   sd
raq_01  2571  0.52  0.52  0.39   0.33  3.5 0.99
raq_03- 2571  0.54  0.54  0.42   0.36  2.5 0.99
raq_04  2571  0.61  0.61  0.53   0.45  3.5 0.99
raq_05  2571  0.64  0.64  0.58   0.48  3.5 1.00
raq_12  2571  0.46  0.46  0.32   0.27  3.5 0.98
raq_16  2571  0.55  0.55  0.44   0.37  3.5 0.98
raq_20  2571  0.61  0.60  0.52   0.44  3.5 1.00
raq_21  2571  0.64  0.65  0.58   0.49  3.5 0.98

Non missing response frequency for each item
          1    2    3    4    5 miss
raq_01 0.02 0.14 0.33 0.35 0.16    0
raq_03 0.02 0.14 0.34 0.34 0.16    0
raq_04 0.02 0.14 0.34 0.34 0.16    0
raq_05 0.03 0.13 0.35 0.32 0.16    0
raq_12 0.02 0.12 0.34 0.35 0.16    0
raq_16 0.02 0.14 0.34 0.34 0.16    0
raq_20 0.02 0.14 0.33 0.35 0.17    0
raq_21 0.02 0.14 0.34 0.35 0.15    0</code></pre>
</div>
</div>
<ul>
<li>note that <code>raq_03-</code> has a minus to indicate reverse scoring</li>
<li>acceptable overall reliability (<span class="math inline">\(\alpha=0.71 [0.69, 0.72]\)</span>)</li>
<li>no items improve the value if they are dropped</li>
<li>item correlations with the total subscale are ok (0.27-0.49)</li>
<li>issue with items not eliciting extreme responses</li>
</ul>



</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-field2023" class="csl-entry" role="listitem">
Field, Andy. 2023. <span>“Discovr: Interactive Tutorials and Data for <span>"</span>Discovering Statistics Using r and RStudio<span>"</span>.”</span>
</div>
<div id="ref-wickham2016" class="csl-entry" role="listitem">
Wickham, Hadley. 2016. <em>Ggplot2: Elegant Graphics for Data Analysis</em>. Springer-Verlag New York. <a href="https://ggplot2.tidyverse.org">https://ggplot2.tidyverse.org</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/cmadland\.github\.io\/blog");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // default icon
          link.classList.add("external");
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>