project:
  type: website
  output-dir: docs
  
execute:
    freeze: true

website:
  title: "Learning | Assessment | Technology"
  site-url: https://cmadland.github.io/blog
  description: "Colin Madland thinks in public."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cmadland/blog
      - icon: bluesky
        href: https://bsky.app/profile/cmad.land
      - icon: rss
        href: index.xml
  draft-mode: unlinked
  repo-url: https://github.com/cmadland/blog
  repo-actions: [source, issue]
format:
  html:
    axe: true
    link-external-icon: true
    code-link: true
    code-copy: true
    theme: flatly
    css: styles.css
    toc: true
    toc-title: On this page
    code-fold: true
    code-summary: "Show the code"
    warning: false
    comments:
      giscus:
        repo: cmadland/blog
        repo-id: R_kgDOLS6tyQ
        category: Announcements
        mapping: pathname
        reactions-enabled: true
        input-position: top
        theme: preferred_color_scheme
        # lang: en
        loading: lazy        
  # pdf: default


