project:
  type: website
  output-dir: docs

execute:
    freeze: true  # re-render only when source changes

website:
  title: "Learning | Assessment | Technology"
  site-url: https://cmadland.github.io/blog
  description: "Colin Madland thinks in public."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cmadland/blog
      - icon: bluesky
        href: https://bsky.app/profile/cmad.land
      - icon: rss
        href: index.xml
  draft-mode: unlinked
format:
  html:
    theme: flatly
    css: styles.css





