project:
  type: website
  output-dir: docs

website:
  title: "Stats Blog"
  site-url: https://cmadland.github.io/blog
  description: "Colins Stats Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cmadland/blog
      - icon: twitter
        href: https://twitter.com/colinmadland
      - icon: rss
        href: index.xml
format:
  html:
    theme: cyborg
    css: styles.css



