<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.545">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Colin Madland">
<meta name="dcterms.date" content="2024-02-26">

<title>Stats Blog - discover_08 - General Linear Model</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Stats Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/cmadland/blog"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/colinmadland"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">discover_08 - General Linear Model</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">regression</div>
                <div class="quarto-category">R</div>
                <div class="quarto-category">discovr</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Colin Madland </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">February 26, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse, ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.0     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>album_tib <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data/album_sales.csv"</span>) <span class="sc">|&gt;</span> readr<span class="sc">::</span><span class="fu">read_csv</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 200 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): album_id
dbl (4): adverts, sales, airplay, image

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>soc_anx_tib <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data/social_anxiety.csv"</span>) <span class="sc">|&gt;</span> readr<span class="sc">::</span><span class="fu">read_csv</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 134 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (4): spai, iii, obq, tosca

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>metal_tib <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data/metal_health.csv"</span>)  <span class="sc">|&gt;</span> readr<span class="sc">::</span><span class="fu">read_csv</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 2506 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (2): hm, suicide

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<section id="fitting-the-linear-model" class="level1">
<h1>Fitting the Linear Model</h1>
<ul>
<li>scatterplots to get an idea of whether assumption of linearity is met, look for outliers or other unusual cases</li>
<li>run an initial regression and save the diagnostics</li>
<li>if we want to generalize or test for significance or confidence intervals…
<ul>
<li>examine residuals for homoscedasticity, independence, normality, and linearity
<ul>
<li>lack of linearity –&gt; fit a non-linear model</li>
<li>assumptions met and no bias –&gt; Model can be generalized</li>
<li>lack of independent errors –&gt; multi-level model</li>
<li>all other situations –&gt; fit a robust version of the model using bootstrapping (small samples) or robust standard errors</li>
</ul></li>
</ul></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="dsr2_fig_08_12_glm_process.png" class="img-fluid figure-img"></p>
<figcaption>General process of fitting a linear model from <code>discovr_08</code></figcaption>
</figure>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>album_tib</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 200 × 5
   album_id adverts sales airplay image
   &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 aox1foms    10.3   330      43    10
 2 u453js2i   986.    120      28     7
 3 pie89xnr  1446.    360      35     7
 4 u2k5a0df  1188.    270      33     7
 5 t4699ux3   575.    220      44     5
 6 s4h49cu2   569.    170      19     5
 7 1235a8sf   472.     70      20     1
 8 p2v24p5k   537.    210      22     9
 9 4fbjg024   514.    200      21     7
10 e9w6usdb   174.    300      40     7
# ℹ 190 more rows</code></pre>
</div>
</div>
<ul>
<li>Use <code>GGally::ggscatmat</code> package to visualize the data</li>
<li>produces
<ul>
<li>a matrix of scatterplots below the diagonal</li>
<li>distributions along the diagonal</li>
<li>the correlation coefficient above the diagonal</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>GGally<span class="sc">::</span><span class="fu">ggscatmat</span>(album_tib, <span class="at">columns =</span> <span class="fu">c</span>(<span class="st">"adverts"</span>, <span class="st">"airplay"</span>, <span class="st">"image"</span>, <span class="st">"sales"</span>))  <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">Interpretation</h2>
<ul>
<li>3 predictors have reasonably linear relationships with album sales and no obvious outliers (except bottom left of ‘band image’ scatterplots)</li>
<li>across the diagonal (distributions)
<ul>
<li>advertising is very skewed</li>
<li>airplay and sales look heavy-tailed</li>
</ul></li>
<li>correlations in the plot give us an idea of the relationships between predictors and outcome</li>
<li>if we ignore album sales, the highest correlation is between image ratings and amount of airplay, which is significant and the 0.01 level (<span class="math inline">\(r=0.18\)</span>)</li>
<li>focussing on the outcome variable, adverts and airplay correlate best with the outcome (<span class="math inline">\(r=0.58\)</span> and <span class="math inline">\(r=0.6\)</span>)</li>
</ul>
</section>
<section id="one-predictor" class="level2">
<h2 class="anchored" data-anchor-id="one-predictor">One predictor</h2>
<section id="fitting-the-model" class="level3">
<h3 class="anchored" data-anchor-id="fitting-the-model">Fitting the model</h3>
<ul>
<li>predicting sales from advertising alone</li>
</ul>
<p><span class="math display">\[Y_i=b_0+{b_1}{X_i}+\epsilon_i\]</span></p>
<p><span class="math display">\[\text{Sales}_i=b_0+{b_1}{\text{Advertising}_i}+\epsilon_i\]</span></p>
<ul>
<li>it is clear from the bottom left scatterplot and the correlation (<span class="math inline">\(r=0.58\)</span>) that a positive relation exists. More advertising money spent leads to greater album sales.</li>
<li>some albums sell well regardless of advertising (top-left of scatterplot)</li>
<li>no albums sell badly when adverts are high (bottom-right of scatterplot)</li>
<li>to fit a linear model, we use <code>lm()</code> function <code>my_model &lt;- lm(outcome ~ predictor(s), data = tibble, na.action = an action)</code>
<ul>
<li><code>my_model</code> is the name of the model</li>
<li><code>outcome</code> is the name of the outcome variable (sales)</li>
<li><code>predictor</code> is the name of the predictor variable (adverts) or, a list of variables separated by <code>+</code> symbols</li>
<li><code>tibble</code> is the name of the tibble containing the data (album_tib)</li>
</ul></li>
<li>this function maps directly to the equation for the model
<ul>
<li><code>adverts ~ sales</code> maps to <span class="math inline">\(\text{Sales}_i=b_0+{b_1}{\text{Advertising}_i}+\epsilon_i\)</span> except we ignore the error term and parameter estimates and we replace the <code>=</code> with <code>~</code> (which means ‘predicted from’)</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>album_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> adverts, <span class="at">data =</span> album_tib, <span class="at">na.action =</span> na.exclude)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(album_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sales ~ adverts, data = album_tib, na.action = na.exclude)

Residuals:
     Min       1Q   Median       3Q      Max 
-152.949  -43.796   -0.393   37.040  211.866 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 1.341e+02  7.537e+00  17.799   &lt;2e-16 ***
adverts     9.612e-02  9.632e-03   9.979   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 65.99 on 198 degrees of freedom
Multiple R-squared:  0.3346,    Adjusted R-squared:  0.3313 
F-statistic: 99.59 on 1 and 198 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">glance</span>(album_lm)  <span class="sc">|&gt;</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 2%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">logLik</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">deviance</th>
<th style="text-align: right;">df.residual</th>
<th style="text-align: right;">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">0.331</td>
<td style="text-align: right;">65.991</td>
<td style="text-align: right;">99.587</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-1120.688</td>
<td style="text-align: right;">2247.375</td>
<td style="text-align: right;">2257.27</td>
<td style="text-align: right;">862264.2</td>
<td style="text-align: right;">198</td>
<td style="text-align: right;">200</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>note <span class="math inline">\(df=1\)</span> and <span class="math inline">\(df.residual=198\)</span> therefore we can say that adding the predictor of advertising significantly improved the fit of the model to the data compared to having no predictors in the model</li>
<li><span class="math inline">\(F(1,198)=99.59, p&lt;.001\)</span></li>
</ul>
</section>
<section id="model-parameters" class="level3">
<h3 class="anchored" data-anchor-id="model-parameters">Model Parameters</h3>
<p>To see model parameters, use <code>broom::tidy()</code></p>
<p><code>broom::tidy(model_name, conf.int = FALSE, conf.level = 0.95)</code></p>
<ul>
<li>put the model name into the function, then two optional arguments
<ul>
<li>confidence intervals <code>conf.int=TRUE</code> (confidence intervals are not included by default)</li>
<li>default is 95%, but you can change it with <code>conf.level=.99</code> for 99% confidence interval</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(album_lm, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term        estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept) 134.       7.54        17.8  5.97e-43 119.       149.   
2 adverts       0.0961   0.00963      9.98 2.94e-19   0.0771     0.115</code></pre>
</div>
</div>
<ul>
<li>output provides estimates of the model parameters (<span class="math inline">\(\hat{b}\)</span>-values)</li>
<li><span class="math inline">\(Y\)</span> intercept (<span class="math inline">\(b_0\)</span>) is 134.14 (when <span class="math inline">\(X\)</span> is 0, sales will be 134140)</li>
<li><span class="math inline">\(X\)</span> (<span class="math inline">\(b_1\)</span>) is 0.096.
<ul>
<li>represents the change in outcome associated with a unit change in predictor.</li>
<li>when the predictor increases by 1, the outcome increases by .096, but since the units of measurement was thousands of pounds and thousands of sales, an increase in $1000 will lead to 96 more albums sold</li>
<li>not very good return</li>
<li>BUT, we know that advertising only accounts for 1/3 of the variance</li>
</ul></li>
<li>If a predictor is having a significant impact on our ability to predict the outcome, then <span class="math inline">\(\hat{b}\)</span> should be different from 0 and large relative to its standard error</li>
<li>the <span class="math inline">\(t\)</span>-test (labelled statistic) and the associated <span class="math inline">\(p\)</span>-value tell us whether the <span class="math inline">\(\hat{b}\)</span> is significantly different from 0</li>
<li>the column p.value contains the exact probability that a value of <span class="math inline">\(t\)</span> at least as big as the one in the table would occur if the value of <span class="math inline">\(b\)</span> in the population were 0</li>
<li>if this propbability is less than 0.05, then we interpret that as the predictor being a significant predictor of hte outcome.</li>
<li>for both <span class="math inline">\(t\)</span>s, the probabilities are in scientific notation
<ul>
<li><code>2.91e-19</code> means <span class="math inline">\(2.91*10^{-19}\)</span>, or <code>move the decimal 19 places to the left</code> or <code>0.000000000000000000291</code></li>
<li><code>2.91e+19</code> means <span class="math inline">\(2.91*10^{19}\)</span>, or <code>move the decimal 19 places to the right</code> or <code>29100000000000000000</code><br>
</li>
</ul></li>
<li>both values are 0 at 3 decimal places</li>
</ul>
</section>
<section id="exploring-the-standard-error-of-hatb" class="level3">
<h3 class="anchored" data-anchor-id="exploring-the-standard-error-of-hatb">Exploring the standard error of <span class="math inline">\(\hat{b}\)</span></h3>
<p>https://www.youtube-nocookie.com/embed/3L9ZMdzJyyI?si=ET90VDYq3RVKnKDq</p>
</section>
<section id="confidence-intervals-for-hatb" class="level3">
<h3 class="anchored" data-anchor-id="confidence-intervals-for-hatb">Confidence intervals for <span class="math inline">\(\hat{b}\)</span></h3>
<p>Imagine we collect 100 samples of data measuring the same variables as the current model, then estimate the same model, including confidence intervals for unstandardized values.The boundaries are constructed such that 95% of our 100 samples contain the population value of <span class="math inline">\(b\)</span>. 95 of 100 sample will yield confidence intervals for <span class="math inline">\(b\)</span> that contain the population value, but we don’t know if our sample is one of the 95.</p>
<p>We might just assume that it does, but if the confidence interval contains 0, then there is a possibility that there is no relationship, or the relationship might be negative. The trouble is that we would be wrong 5% of the time.</p>
<p>If the interval does not contain 0, we might conclude there is a genuine positive relationship.</p>
</section>
<section id="using-the-model" class="level3">
<h3 class="anchored" data-anchor-id="using-the-model">Using the model</h3>
<p><span class="math display">\[\text{Sales}_i=\hat{b_0}+\hat{b_1}{\text{Advertising}_i}\]</span></p>
<p><span class="math display">\[\text{Sales}_i=134.14+.096*{Advertising}_i\]</span></p>
<p>Now we can make a prediction by entering a value for the advertising budget, say 100 (equal to 100,000 gbp)</p>
<p><span class="math display">\[\text{Sales}_i=134.14+.096*{100}_i\]</span></p>
<p><span class="math display">\[\text{Sales}_i=143.74\]</span> or 143,740 sales</p>
</section>
</section>
<section id="several-predictors" class="level2">
<h2 class="anchored" data-anchor-id="several-predictors">Several Predictors</h2>
<p>add multiple predictors hierarchically, after advertising is shown to be significant</p>
<p><span class="math display">\[Y_i=b_0+{b_1}{X_1i}+{b_2}{X_2i}+{b_3}{X_3i}+ ... +{b_n}{X_ni}\epsilon_i\]</span></p>
<p><span class="math display">\[Y_i=b_0+{b_1}{advertising_i}+{b_2}{airplay_i}+{b_3}{image_i}+\epsilon_i\]</span></p>
<section id="building-the-model" class="level3">
<h3 class="anchored" data-anchor-id="building-the-model">Building the model</h3>
<ul>
<li>add predictors to the R code the same way as we do in the equation, by adding <code>+</code></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>album_full_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> adverts <span class="sc">+</span> airplay <span class="sc">+</span> image, <span class="at">data =</span> album_tib, <span class="at">na.action =</span> na.exclude)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(album_full_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sales ~ adverts + airplay + image, data = album_tib, 
    na.action = na.exclude)

Residuals:
     Min       1Q   Median       3Q      Max 
-121.324  -28.336   -0.451   28.967  144.132 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -26.612958  17.350001  -1.534    0.127    
adverts       0.084885   0.006923  12.261  &lt; 2e-16 ***
airplay       3.367425   0.277771  12.123  &lt; 2e-16 ***
image        11.086335   2.437849   4.548 9.49e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 47.09 on 196 degrees of freedom
Multiple R-squared:  0.6647,    Adjusted R-squared:  0.6595 
F-statistic: 129.5 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">glance</span>(album_full_lm)  <span class="sc">|&gt;</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 2%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">logLik</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">deviance</th>
<th style="text-align: right;">df.residual</th>
<th style="text-align: right;">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.665</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;">47.087</td>
<td style="text-align: right;">129.498</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">-1052.168</td>
<td style="text-align: right;">2114.337</td>
<td style="text-align: right;">2130.828</td>
<td style="text-align: right;">434574.6</td>
<td style="text-align: right;">196</td>
<td style="text-align: right;">200</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li><code>r.squared</code> <span class="math inline">\(R^2\)</span> tells us the variance in album sales -&gt; .665, or 66.5%.</li>
<li><span class="math inline">\(R^2\)</span> for adverts was 0.335, so the difference -&gt; .665-.335=.33 means that airplay and image account for a further 33% of the variance</li>
<li>adjusted <span class="math inline">\(R^2\)</span> <code>adj.r.squared</code> tells us how well the model generalizes, and the value should be close to r.squared.
<ul>
<li>in this case it is .66, or only .005 away</li>
</ul></li>
<li><span class="math inline">\(F\)</span>-statistic is the ratio of the improvementin prediction that results from fitting the model, relative to the inaccuracy that sitll exists in the model</li>
<li>the variable <code>p.value</code> contains the p-value associated with <span class="math inline">\(F\)</span> -&gt; in this case is <span class="math inline">\(2.88×10^{−46}\)</span> -&gt; much smaller than .001</li>
<li>degrees of freedom are <code>df</code> and <code>df.residual</code></li>
<li>we can interpret the result as meaning that the model significantly improves our ability to predict the outcome variable ocmpared to not fitting the model.</li>
<li>reported as <span class="math inline">\(F(3, 196)=129.5, p=&lt;0.001\)</span></li>
</ul>
</section>
</section>
<section id="comparing-models" class="level2">
<h2 class="anchored" data-anchor-id="comparing-models">Comparing Models</h2>
<ul>
<li>we can compare hierarchical models using an <span class="math inline">\(F\)</span>-statisticusing the <code>anova()</code> function -&gt; <code>anova(model_1, model_2, … , model_n)</code></li>
<li>list the models in order that we want to compare</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(album_lm, album_full_lm) <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term                      df.residual    rss    df   sumsq statistic   p.value
  &lt;chr&gt;                           &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 sales ~ adverts                   198 8.62e5    NA     NA       NA   NA       
2 sales ~ adverts + airpla…         196 4.35e5     2 427690.      96.4  6.88e-30</code></pre>
</div>
</div>
<ul>
<li><span class="math inline">\(F\)</span> (<code>statistic</code>) is 96.5</li>
<li><span class="math inline">\(p\)</span>-value (<code>p.value</code>) is <span class="math inline">\(6.8793949^{-30}\)</span></li>
<li><code>df</code> is 2 (difference between df in 2 models)</li>
<li><code>df.residual</code> is 196</li>
<li>Conclusion -&gt; adding airplay and image to the model significantly improved model fit
<ul>
<li><span class="math inline">\(F(2, 196) = 96.45, p &lt; 0.001\)</span></li>
</ul></li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>We can only compare hierarchical models; that is to say that the second model must contain everything that was in the first model plus something new, and the third model must contain everything in the second model plus something new, and so on.</p>
</div>
</div>
<section id="model-parameter-estimates-hatb" class="level3">
<h3 class="anchored" data-anchor-id="model-parameter-estimates-hatb">Model parameter estimates (<span class="math inline">\(\hat{b}\)</span>)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(album_full_lm, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)  <span class="sc">|&gt;</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-26.613</td>
<td style="text-align: right;">17.350</td>
<td style="text-align: right;">-1.534</td>
<td style="text-align: right;">0.127</td>
<td style="text-align: right;">-60.830</td>
<td style="text-align: right;">7.604</td>
</tr>
<tr class="even">
<td style="text-align: left;">adverts</td>
<td style="text-align: right;">0.085</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">12.261</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.071</td>
<td style="text-align: right;">0.099</td>
</tr>
<tr class="odd">
<td style="text-align: left;">airplay</td>
<td style="text-align: right;">3.367</td>
<td style="text-align: right;">0.278</td>
<td style="text-align: right;">12.123</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">2.820</td>
<td style="text-align: right;">3.915</td>
</tr>
<tr class="even">
<td style="text-align: left;">image</td>
<td style="text-align: right;">11.086</td>
<td style="text-align: right;">2.438</td>
<td style="text-align: right;">4.548</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">6.279</td>
<td style="text-align: right;">15.894</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>output gives estimates of the <span class="math inline">\(b\)</span>-balues (column labelled <code>estimate</code>) and statistics that indicate the individual contribution of each predictor in the model.</li>
<li>all three predictors have positive <span class="math inline">\(\hat{b}\)</span>values, indicating positive relationships
<ul>
<li>as all three predictors increase, so do album sales</li>
</ul></li>
<li><span class="math inline">\(\hat{b}\)</span> vlaues also tell us to what degree each predictor affects the outcome if the effects of all other predictors are held constant
<ul>
<li>advertising budget -&gt; <span class="math inline">\(\hat{b}=0.085\)</span> -&gt; as advertising increases by 1 unit (1000gbp), sales increases by 0.085 units (85 albums), but this is only true if the other two predictors are held constant</li>
<li>airplay <span class="math inline">\(\hat{b}=3.367\)</span> -&gt; as airplay prior to release increases by one unit (1 play), album sales increase by 3.367 units (3367 album sales, but only if the other two predictors are held constant)</li>
</ul></li>
</ul>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How would we interpret the 𝑏̂ (11.086) for band image?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If a band can increase their image rating by 1 unit they can expect additional album sales of 11,086 units</p>
</div>
</div>
</div>
</section>
<section id="standardized-hatbs" class="level3">
<h3 class="anchored" data-anchor-id="standardized-hatbs">Standardized <span class="math inline">\(\hat{b}\)</span>s</h3>
<p>The <code>lm()</code> function does not provide standardized betas, so use <code>model_parameters()</code></p>
<p><code>parameters::model_parameters(my_model, standardize = refit)</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>parameters<span class="sc">::</span><span class="fu">model_parameters</span>(album_full_lm, <span class="at">standardize =</span> <span class="st">"refit"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Coefficient</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
<th style="text-align: right;">t</th>
<th style="text-align: right;">df_error</th>
<th style="text-align: right;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.041</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.081</td>
<td style="text-align: right;">0.081</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">196</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">adverts</td>
<td style="text-align: right;">0.511</td>
<td style="text-align: right;">0.042</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.429</td>
<td style="text-align: right;">0.593</td>
<td style="text-align: right;">12.261</td>
<td style="text-align: right;">196</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">airplay</td>
<td style="text-align: right;">0.512</td>
<td style="text-align: right;">0.042</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.429</td>
<td style="text-align: right;">0.595</td>
<td style="text-align: right;">12.123</td>
<td style="text-align: right;">196</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">image</td>
<td style="text-align: right;">0.192</td>
<td style="text-align: right;">0.042</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.109</td>
<td style="text-align: right;">0.275</td>
<td style="text-align: right;">4.548</td>
<td style="text-align: right;">196</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>advertising budget -&gt; Standardized <span class="math inline">\(\hat{\beta}=0.511\)</span>
<ul>
<li>as the advertising budgetr increases by one standard deviation (485,655gbp), album sales increase by .511 standard deviations.</li>
<li>the standard deviation for album sales is 80,699, so .511 SD is 41,240 sales</li>
<li>for every increase in advert budget of 485655gbp, album sales will increase by 41,240 IF the other predictors are held constant</li>
</ul></li>
<li>Image -&gt; Standardized <span class="math inline">\(\hat{\beta}=0.192\)</span>
<ul>
<li>a band rated 1 SD on the image scale (1.4 units) will sell .192 SD more units.</li>
<li>this is a change of 15,490 sales IF the other predictors are held constant</li>
</ul></li>
</ul>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How would we interpret the Standardized B (0.512) for airplay?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>As the number of plays on radio in the week before release increases by 1 standard deviation, album sales increase by 0.512 standard deviations</p>
</div>
</div>
</div>
</section>
<section id="confidence-intervals" class="level3">
<h3 class="anchored" data-anchor-id="confidence-intervals">Confidence Intervals</h3>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The confidence interval for airplay ranges from 2.82 to 3.92. What does this tell us?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><del>The probability of this confidence interval containing the population value is 0.95.</del></li>
<li>If this confidence interval is one of the 95% that contains the population value then the population value of b lies between 2.82 and 3.92.</li>
<li><del>I can be 95% confident that the population value of b lies between 2.82 and 3.92</del></li>
<li><del>There is a 95% chance that the population value of b lies between 2.82 and 3.92</del></li>
</ul>
</div>
</div>
</div>
<p>Assuming that each confidence interval is one of the 95% that contains the population parameter: - the true size of the relationship between advertising budget and album sales lies somewhere between 0.071 and 0.099 - the true size of the relationship between band image and album sales lies somewhere between 6.279 and 15.894</p>
<ul>
<li>the two best predictors have tight confidence intervals (airplay and adverts) indicating that the estimates are likely representative of the true population values</li>
<li>the interval for band image is much wider, but does not cross zero indicating this parameter is less representative of the population, but is still significant.</li>
</ul>
</section>
<section id="significance-tests" class="level3">
<h3 class="anchored" data-anchor-id="significance-tests">Significance tests</h3>
<p>The values in <code>statistic</code> are the values of <span class="math inline">\(t\)</span> associated with each <span class="math inline">\(\hat{b}\)</span> and <code>p.value</code> is the associated significance of the <span class="math inline">\(t\)</span>-statistic. For every predictor, the <span class="math inline">\(\hat{b}\)</span> is significantly different from 0 (<span class="math inline">\(p&lt;.001\)</span>) meaning that all predictors significantly predict album sales.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How might we interpret the statistic and p.value for the three predictors?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><del>The probability of the null hypothesis is less than 0.001 in all cases</del></li>
<li><del>The probability that each b is a chance result is less than 0.001</del></li>
<li>They tell us that the probability of getting a value of t at least as big as these values if the value of b were, in fact, zero is smaller than 0.001 for all predictors.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="math inline">\(p\)</span>-values
</div>
</div>
<div class="callout-body-container callout-body">
<p>Many students and researchers think of <em>p</em>-values in terms of the ‘probability of a chance result’ or ‘the probability of a hypothesis being true’ but they are neither of these things. <u><strong>They are the long-run probability that you would get a test-statistic (in this case <em>t</em>) at least as large as the one you have if the null hypothesis were true.</strong></u> In other words, if there really were no relationship between advertising budget and album sales (the null hypothesis) then the population value of <em>b</em> would be zero.</p>
<p>Imagine we sampled from this null population and computed <em>t</em>, and then repeated this process 1000 times. We’d have 1000 values of <em>t</em> from a population in which there was no effect. We could plot these values as a histogram. This would tell us how often certain values of <em>t</em> occur. From it we could work out the probability of getting a particular value of <em>t</em>. If we then took another sample, and computed <em>t</em> (because we’re kind of obsessed with this sort of thing) we would be able to compare this value of <em>t</em> to the distribution of all the previous 1000 samples. Is the <em>t</em> in our current sample large of small compared to the others? Let’s say it was larger than 999 of the previous values. That would be quite an unlikely value of <em>t</em> whereas if it was larger than 500 of them this would not surprise us. <u><strong>This is what a <em>p</em>-value is: it is the long run probability of getting test statistic at least as large as the one you have if the null hypothesis were true.</strong></u> If the value is less than 0.05, people typically take this as supporting the idea that the null hypothesis isn’t true.</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Report
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>the model that included the band’s image and airplay was significantly better fit than the model that included advertising budget alone <span class="math inline">\(f(2, 196)=96.45, p&lt;0.001\)</span></li>
<li>the final model explained 66.5% of the variance in album sales</li>
<li>advertising budget significantly predicted album sales <span class="math inline">\(\hat{b}=0.08[0.07, 0.10], t(196)=12.26, p&gt;.001\)</span></li>
<li>airplay significantly predicted album sales <span class="math inline">\(\hat{b}=3.37[2.82, 3.92], t(196)=12.12, p&lt;.001\)</span></li>
<li>band image significantly predicted album sales -&gt; <span class="math inline">\(\hat{b}=11.09[6.28, 15.89], t=4.55, p&lt;.001\)</span></li>
</ul>
</div>
</div>
</section>
</section>
<section id="unguided-example" class="level2">
<h2 class="anchored" data-anchor-id="unguided-example">Unguided Example</h2>
<section id="metal-and-mental-health" class="level3">
<h3 class="anchored" data-anchor-id="metal-and-mental-health">Metal and mental health</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>metal_tib</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,506 × 2
      hm suicide
   &lt;dbl&gt;   &lt;dbl&gt;
 1    10       7
 2    10      11
 3    10       8
 4     4      14
 5    10      13
 6     8      12
 7     8       7
 8     5      15
 9     8       7
10     9      10
# ℹ 2,496 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>GGally<span class="sc">::</span><span class="fu">ggscatmat</span>(metal_tib, <span class="at">columns=</span><span class="fu">c</span>(<span class="st">"hm"</span>, <span class="st">"suicide"</span>)) <span class="sc">+</span> <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 200 rows containing non-finite outside the scale range
(`stat_density()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 284 rows containing non-finite outside the scale range
(`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>metal_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(suicide <span class="sc">~</span> hm, <span class="at">data =</span> metal_tib, <span class="at">na.action =</span> na.exclude)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">glance</span>(metal_lm) <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 5%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 2%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">logLik</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">deviance</th>
<th style="text-align: right;">df.residual</th>
<th style="text-align: right;">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.125</td>
<td style="text-align: right;">0.125</td>
<td style="text-align: right;">4.842</td>
<td style="text-align: right;">304.784</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-6401.851</td>
<td style="text-align: right;">12809.7</td>
<td style="text-align: right;">12826.7</td>
<td style="text-align: right;">50047.05</td>
<td style="text-align: right;">2135</td>
<td style="text-align: right;">2137</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(metal_lm, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level=</span><span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term        estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)   16.0      0.261       61.4 0          15.5      16.5  
2 hm            -0.612    0.0350     -17.5 6.64e-64   -0.680    -0.543</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How much variance does the final model explain?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>12.5%</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What is the nature of the relationship between listening to heavy metal and suicide risk?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>As love of heavy metal increases, suicide risk decreases</li>
<li>because the <span class="math inline">\(\hat{b}\)</span> value is negative (-.0612)</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
As listening to heavy metal increases by 1 unit, by how much does suicide risk change?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>-0.612 units</li>
</ul>
</div>
</div>
</div>
</section>
<section id="predicting-social-anxiety" class="level3">
<h3 class="anchored" data-anchor-id="predicting-social-anxiety">Predicting Social Anxiety</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>soc_anx_tib</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 134 × 4
    spai   iii   obq tosca
   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1    26 56.5   4.43  4.18
 2    51 16.1   2.03  4.20
 3    33 37.4   2.59  3.25
 4   106 16.7   4.84  4.07
 5    25  5.16  1.76  3.80
 6   109 36.0   2.13  4.25
 7    39 34.5   2.01  4.95
 8   134 18.0   1.76  4.52
 9    43 12.9   2.29  3.59
10    57  7.10  3.20  3.64
# ℹ 124 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>GGally<span class="sc">::</span><span class="fu">ggscatmat</span>(soc_anx_tib, <span class="at">columns =</span> <span class="fu">c</span>(<span class="st">"spai"</span>, <span class="st">"tosca"</span>))  <span class="sc">+</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>soc_anx_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(spai <span class="sc">~</span> tosca, <span class="at">data =</span> soc_anx_tib, <span class="at">na.action =</span> na.exclude)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">glance</span>(soc_anx_lm)  <span class="sc">|&gt;</span> </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 2%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">logLik</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">deviance</th>
<th style="text-align: right;">df.residual</th>
<th style="text-align: right;">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.102</td>
<td style="text-align: right;">0.095</td>
<td style="text-align: right;">29.918</td>
<td style="text-align: right;">14.989</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-644.525</td>
<td style="text-align: right;">1295.05</td>
<td style="text-align: right;">1303.743</td>
<td style="text-align: right;">118153.3</td>
<td style="text-align: right;">132</td>
<td style="text-align: right;">134</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(soc_anx_lm, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term        estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)    -54.8     30.0      -1.82 0.0703     -114.       4.60
2 tosca           27.4      7.08      3.87 0.000169     13.4     41.4 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>soc_anx_obq_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(spai <span class="sc">~</span> tosca <span class="sc">+</span> obq, <span class="at">data =</span> soc_anx_tib, <span class="at">na.action =</span> na.exclude)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">glance</span>(soc_anx_obq_lm)  <span class="sc">|&gt;</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 2%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">logLik</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">deviance</th>
<th style="text-align: right;">df.residual</th>
<th style="text-align: right;">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.148</td>
<td style="text-align: right;">0.135</td>
<td style="text-align: right;">29.015</td>
<td style="text-align: right;">11.218</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">-630.333</td>
<td style="text-align: right;">1268.666</td>
<td style="text-align: right;">1280.197</td>
<td style="text-align: right;">108599.6</td>
<td style="text-align: right;">129</td>
<td style="text-align: right;">132</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(soc_anx_obq_lm, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  term        estimate std.error statistic p.value conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)   -53.3      29.2      -1.82 0.0704   -111.        4.50
2 tosca          22.1       7.24      3.05 0.00276     7.77     36.4 
3 obq             7.25      2.91      2.49 0.0141      1.49     13.0 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>parameters<span class="sc">::</span><span class="fu">model_parameters</span>(soc_anx_obq_lm, <span class="at">standardize =</span> <span class="st">"refit"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Coefficient</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">CI</th>
<th style="text-align: right;">CI_low</th>
<th style="text-align: right;">CI_high</th>
<th style="text-align: right;">t</th>
<th style="text-align: right;">df_error</th>
<th style="text-align: right;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.081</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.160</td>
<td style="text-align: right;">0.160</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">129</td>
<td style="text-align: right;">1.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">tosca</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">0.086</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.092</td>
<td style="text-align: right;">0.430</td>
<td style="text-align: right;">3.052</td>
<td style="text-align: right;">129</td>
<td style="text-align: right;">0.003</td>
</tr>
<tr class="odd">
<td style="text-align: left;">obq</td>
<td style="text-align: right;">0.213</td>
<td style="text-align: right;">0.086</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.044</td>
<td style="text-align: right;">0.382</td>
<td style="text-align: right;">2.489</td>
<td style="text-align: right;">129</td>
<td style="text-align: right;">0.014</td>
</tr>
</tbody>
</table>
</div>
</div>
<pre><code>anova(soc_anx_lm, soc_anx_obq_lm) |&gt;
broom::tidy()</code></pre>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Error message
</div>
</div>
<div class="callout-body-container callout-body">
<p>Error in anova.lmlist(object, …) : models were not all fitted to the same size of dataset</p>
<ul>
<li><p>as of this writing (Mar-04-24), there is a solution listed in the <code>discovr_08</code> tutorial to start by finding the error with <code>soc_anx_tib |&gt; dplyr::summarise( across(.fns = list(valid = ~sum(!is.na(.x)), missing = ~sum(is.na(.x))), .names = "{.col}_{.fn}") )</code></p>
<ul>
<li>The output from running this function in the tutorial is a table showing that there are missing values in <code>obq</code>. this means that <code>spai</code> and <code>tosca</code> have 134 values and <code>obq</code> has 132 values, so they are not the same size.</li>
</ul></li>
<li><p>However, the output above in my own .qmd file throws a <code>deprecated</code> error in <code>dplyr 1.1.4</code> that the use of <code>across</code> without <code>.cols</code> is deprecated since <code>dplyr 1.1.1</code></p></li>
<li><p>this means that I can’t currently generate the table showing the sizes of the datasets with the code provided</p></li>
<li><p>the workaround to the problem is normally to use <code>multiple imputation</code> to estimate the missing values, which is beyond the scope of this tutorial, so Field recommends a <code>very bad practice</code>, which is to omit the missing values.</p></li>
<li><p>I’ve <a href="https://github.com/profandyfield/discovr/issues/17">filed an issue in the <code>discover.rocks</code> repo</a></p></li>
</ul>
</div>
</div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>